import { execFileSync } from "node:child_process"; import { writeFileSync } from "node:fs";
const UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/153 Safari/537.36"; const out={pages:[],scripts:[],candidates:[],responses:[],errors:[]};
function curl(args){try{return execFileSync("curl",["--silent","--show-error","--compressed","--connect-timeout","12","--max-time","30","-A",UA,...args],{encoding:"utf8",maxBuffer:30000000})}catch(e){return "CURL_ERROR:"+String(e)}}
function get(url){return curl(["-L","-H","Accept: */*","-H","Referer: https://www.apple.com/in/shop/buy-iphone/iphone-17",url])}
function hasProduct(text){const x=String(text||"").toLowerCase();return ["productid","productnumber","partnumber","sku","finalprice","price","catalog","inventory","fulfillment","product"].some(k=>x.includes(k))}
function snippets(text,needles){const out=[];const low=String(text||"").toLowerCase();for(const n of needles){let p=0;const nn=n.toLowerCase();while((p=low.indexOf(nn,p))>=0){out.push(text.slice(Math.max(0,p-220),Math.min(text.length,p+n.length+450)));p+=nn.length;if(out.length>=150)break}}return out}
function scriptUrls(text,base){const result=[];let p=0;while(true){const a=text.indexOf("<script",p);if(a<0)break;const b=text.indexOf(">",a);if(b<0)break;const tag=text.slice(a,b+1);const k=tag.toLowerCase().indexOf("src=");if(k>=0){const q=tag[k+4];if(q===String.fromCharCode(34)||q===String.fromCharCode(39)){const e=tag.indexOf(q,k+5);if(e>k){try{result.push(new URL(tag.slice(k+5,e),base).href)}catch{}}}}p=b+1}return [...new Set(result)]}
function quotedCandidates(text){const out=[];for(const q of [String.fromCharCode(34),String.fromCharCode(39)]){let p=0;while((p=text.indexOf(q,p))>=0){const e=text.indexOf(q,p+1);if(e<0)break;const s=text.slice(p+1,e);if(s.length>=4&&s.length<=240&&["/shop/","/api/","product","catalog","price","inventory","fulfillment","availability","sba/","search"].some(k=>s.toLowerCase().includes(k))&&!out.includes(s))out.push(s);p=e+1;if(out.length>=300)break}}return out}
for(const u of ["https://www.apple.com/in/shop/buy-iphone/iphone-17","https://www.apple.com/in/shop/buy-iphone/iphone-17-pro"]){const t=get(u);const ss=scriptUrls(t,u);out.pages.push({url:u,bytes:t.length,scripts:ss.length,productFields:hasProduct(t)});for(const s of ss.slice(0,140)){try{const x=get(s);const hits=snippets(x,["/shop/","fulfillment","inventory","availability","pricing","finalPrice","product","catalog","commerce","sba/","search","api"]);if(hits.length)out.scripts.push({url:s,bytes:x.length,hits:hits.slice(0,100)});for(const e of quotedCandidates(x))if(!out.candidates.includes(e))out.candidates.push(e)}catch(e){out.errors.push({stage:"script",url:s,error:String(e)})}}}
for(const u of ["https://www.apple.com/in/shop/sba/d/init","https://www.apple.com/in/shop/fulfillment-messages?fae=true&mts.0=pincode","https://www.apple.com/in/shop/search?query=iphone","https://www.apple.com/shop/fulfillment-messages","https://www.apple.com/search-services/suggestions/"]){const t=get(u);out.responses.push({url:u,bytes:t.length,productish:hasProduct(t),sample:t.slice(0,10000)})}
for(const e of out.candidates.slice(0,220)){let u="";try{u=new URL(e,"https://www.apple.com/in/").href}catch{continue}const host=new URL(u).hostname.toLowerCase();if(!host.endsWith("apple.com"))continue;const path=u.toLowerCase();if(!(path.includes("/shop/")||path.includes("/api/")||path.includes("product")||path.includes("catalog")||path.includes("fulfillment")))continue;try{const t=get(u);if(t.length<800000)out.responses.push({url:u,bytes:t.length,productish:hasProduct(t),sample:t.slice(0,8000)})}catch{}}
writeFileSync("apple-hunt.json",JSON.stringify(out,null,2)); console.log(JSON.stringify({pages:out.pages,scripts:out.scripts.length,candidates:out.candidates.length,responses:out.responses.length,productResponses:out.responses.filter(x=>x.productish).map(x=>x.url).slice(0,100)},null,2));