import { chromium } from "playwright"; import { writeFileSync } from "node:fs";
const UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/153 Safari/537.36"; const out={pages:[],network:[],globals:[],scripts:[],direct:[],errors:[]};
function trim(s,n=12000){return String(s||"").slice(0,n)}
const b=await chromium.launch({headless:true}); const c=await b.newContext({userAgent:UA,locale:"en-IN",viewport:{width:1440,height:1200}}); const p=await c.newPage();
p.on("response",async r=>{try{const q=r.request(),u=r.url(),ct=r.headers()["content-type"]||"";if(!/xhr|fetch/i.test(q.resourceType())&&!/api|rome|discover|search|product|listing|page|catalog/i.test(u))return;const x={url:u,status:r.status(),method:q.method(),resourceType:q.resourceType(),ct};if(q.postData())x.postData=trim(q.postData(),10000);if(/json|text|javascript/i.test(ct)&&r.status()<500){try{x.body=trim(await r.text());x.productish=/(productId|pid|sku|price|sellingPrice|mrp|listingId|productInfo|product)/i.test(x.body)}catch{}}out.network.push(x)}catch{}});
for(const u of ["https://www.flipkart.com/search?q=laptop","https://www.flipkart.com/laptops/pr?sid=6bo,b5g"]){try{const r=await p.goto(u,{waitUntil:"domcontentloaded",timeout:90000});await p.waitForTimeout(7000);const html=await p.content();out.pages.push({url:u,status:r?.status()||null,final:p.url(),bytes:html.length,scriptSrcs:[...html.matchAll(/<script\\b[^>]+src=["\']([^"\']+)["\']/gi)].map(m=>new URL(m[1],p.url()).href).slice(0,150),stateScriptSnippets:[...html.matchAll(/<script[^>]*>([\\s\\S]*?)<\\/script>/gi)].map(m=>m[1]).filter(x=>/(productId|sellingPrice|mrp|listingId|initial|state|searchPage)/i.test(x)).slice(0,30).map(x=>trim(x,10000))});
const globals=await p.evaluate(()=>Object.keys(window).filter(k=>/state|product|search|listing|redux|apollo|preload|initial|page/i.test(k)).slice(0,200).map(k=>{let v;try{v=window[k]}catch{};return {k,type:typeof v,preview:typeof v==="string"?v.slice(0,200):Array.isArray(v)?`array:${v.length}`:v&&typeof v==="object"?Object.keys(v).slice(0,30):null}}));out.globals.push({url:u,globals});
await p.mouse.wheel(0,10000);await p.waitForTimeout(4000);await p.mouse.wheel(0,10000);await p.waitForTimeout(4000);
for(const s of ["button:has-text(\"Next\")","a:has-text(\"Next\")"]){const l=p.locator(s).first();if(await l.count()&&await l.isVisible().catch(()=>false)){try{await l.click({timeout:2000});await p.waitForTimeout(4000)}catch{}}}
}catch(e){out.errors.push({url:u,error:String(e)})}}
for(const u of ["https://2.rome.api.flipkart.com/api/4/discover/autosuggest","https://2.rome.api.flipkart.com/api/4/discover/search","https://2.rome.api.flipkart.com/api/4/discover/products","https://2.rome.api.flipkart.com/api/4/search"]){for(const body of [JSON.stringify({query:"laptop",contextUri:"/search?q=laptop",marketPlaceId:"FLIPKART",rows:40}),JSON.stringify({query:"laptop",q:"laptop",rows:40})]){try{const r=await fetch(u,{method:"POST",headers:{"user-agent":UA,"content-type":"application/json","accept":"application/json","origin":"https://www.flipkart.com","referer":"https://www.flipkart.com/search?q=laptop"},body});const t=await r.text();out.direct.push({url:u,status:r.status,ct:r.headers.get("content-type"),bytes:t.length,productish:/(productId|pid|sku|price|sellingPrice|mrp|listingId|product)/i.test(t),sample:trim(t,10000),body})}catch(e){out.errors.push({stage:"direct",url:u,error:String(e)})}}}
await p.close();await b.close();writeFileSync("flipkart-hunt.json",JSON.stringify(out,null,2));console.log(JSON.stringify({pages:out.pages.length,network:out.network.length,productNetwork:out.network.filter(x=>x.productish).map(x=>x.url),scripts:out.scripts.length,direct:out.direct.length,productDirect:out.direct.filter(x=>x.productish).map(x=>x.url),errors:out.errors.length},null,2));