import { chromium } from "playwright"; import { writeFile } from "node:fs/promises";
const UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/153 Safari/537.36";
const OUT={apple:{pages:[],scripts:[],network:[],direct:[],errors:[]},flipkart:{pages:[],scripts:[],network:[],direct:[],errors:[]},acer:{direct:[],errors:[]}};
function trim(s,n=7000){return String(s||"").slice(0,n)} function prod(t){return /(?:productId|productCode|sku|finalPrice|sellingPrice|mrp|price|modelCode|catalog|products|listingId|productName)/i.test(t)}
async function req(url,opt={}){const r=await fetch(url,{redirect:"follow",headers:{"user-agent":UA,"accept":"*/*",...(opt.headers||{})},...opt});const text=await r.text();return {url:r.url,status:r.status,ct:r.headers.get("content-type")||"",text,headers:Object.fromEntries(r.headers.entries())}}
async function pageProbe(label,urls,out){const b=await chromium.launch({headless:true});const c=await b.newContext({userAgent:UA,locale:"en-IN",viewport:{width:1440,height:1200}});const p=await c.newPage();p.on("response",async res=>{try{const q=res.request(),u=res.url(),ct=res.headers()["content-type"]||"";if(!/xhr|fetch/i.test(q.resourceType())&&!/api|graphql|rome|product|search|catalog|price|inventory|listing/i.test(u))return;const row={url:u,status:res.status(),method:q.method(),type:q.resourceType(),ct};if(q.postData())row.postData=trim(q.postData(),12000);if(/json|text|javascript|octet-stream/i.test(ct)&&res.status()<500){try{row.body=trim(await res.text(),16000)}catch{}}out.network.push(row)}catch{}});for(const u of urls){try{const r=await p.goto(u,{waitUntil:"domcontentloaded",timeout:90000});await p.waitForTimeout(4500);const html=await p.content();out.pages.push({requested:u,status:r?.status()??null,final:p.url(),htmlBytes:html.length,buttons:(await p.locator("button").allTextContents()).filter(x=>x.trim()).slice(0,80),inputs:await p.locator("input").evaluateAll(xs=>xs.slice(0,40).map(x=>({type:x.type,name:x.name,aria:x.getAttribute("aria-label"),value:x.value,ph:x.placeholder}))),markers:{productId:prod(html),graphql:/graphql/i.test(html),commerce:/commerce|sba|fulfillment/i.test(html)}});
if(label==="Flipkart"){await p.mouse.wheel(0,6000);await p.waitForTimeout(3500);await p.mouse.wheel(0,6000);await p.waitForTimeout(3500);for(const sel of ["a[href*=\"page=2\"]","button:has-text(\"Next\")","a:has-text(\"2\")"]){const l=p.locator(sel).first();if(await l.count()&&await l.isVisible().catch(()=>false)){try{await l.click();await p.waitForTimeout(4500)}catch{}}}}
if(label==="Apple"){for(const s of ["button","input[type=\"radio\"]","label"]){const vals=await p.locator(s).allTextContents().catch(()=>[]);out.pages.push({selector:s,texts:vals.filter(x=>/GB|TB|storage|color|black|white|blue|pro|air/i.test(x)).slice(0,80)})};
for(const s of ["input[type=\"radio\"]","button"]){const loc=p.locator(s);const n=Math.min(await loc.count(),80);for(let i=0;i<n;i++){const x=loc.nth(i);const txt=trim(await x.innerText().catch(()=>""),120);if(/GB|TB|storage/i.test(txt)){try{await x.click({timeout:1500});await p.waitForTimeout(2500);break}catch{}}}}}}
}catch(e){out.errors.push({url:u,error:String(e)})}}await b.close()}
async function scripts(url,out){try{const r=await req(url,{headers:{accept:"text/html"}});const ss=[...r.text.matchAll(/<script\\b[^>]+src=["\']([^"\']+)["\']/gi)].map(m=>new URL(m[1],r.url).href);for(const s of [...new Set(ss)].slice(0,100)){try{const x=await req(s,{headers:{accept:"application/javascript,text/javascript,*/*"}});const hits=[...x.text.matchAll(/.{0,140}(?:\\/shop\\/sba|fulfillment|inventory|availability|pricing|price|product|catalog|graphql|api-www|search-services|\.json).{0,220}/gi)].slice(0,80).map(m=>trim(m[0],700));if(hits.length)out.scripts.push({url:s,status:x.status,bytes:x.text.length,hits})}catch{}}}catch(e){out.errors.push({stage:"scripts",url,error:String(e)})}}
async function apple(){await pageProbe("Apple",["https://www.apple.com/in/shop/buy-iphone/iphone-17","https://www.apple.com/in/shop/buy-iphone/iphone-17-pro"],OUT.apple);await scripts("https://www.apple.com/in/shop/buy-iphone/iphone-17",OUT.apple);await scripts("https://www.apple.com/in/shop/buy-iphone/iphone-17-pro",OUT.apple);for(const u of ["https://www.apple.com/in/shop/sba/d/init","https://www.apple.com/in/shop/fulfillment-messages?fae=true&mts.0=pincode","https://www.apple.com/shop/fulfillment-messages","https://www.apple.com/in/shop/search?query=iphone"]){try{const r=await req(u,{headers:{accept:"application/json,text/plain,*/*",referer:"https://www.apple.com/in/shop/buy-iphone/iphone-17"}});OUT.apple.direct.push({url:r.url,status:r.status,ct:r.ct,bytes:r.text.length,productish:prod(r.text),sample:trim(r.text,10000)})}catch(e){OUT.apple.errors.push({stage:"direct",url:u,error:String(e)})}}}
async function flipkart(){await pageProbe("Flipkart",["https://www.flipkart.com/search?q=laptop","https://www.flipkart.com/laptops/pr?sid=6bo,b5g"],OUT.flipkart);await scripts("https://www.flipkart.com/search?q=laptop",OUT.flipkart);const urls=["https://2.rome.api.flipkart.com/api/4/discover/search","https://2.rome.api.flipkart.com/api/4/discover/search?query=laptop","https://2.rome.api.flipkart.com/api/4/discover/products","https://2.rome.api.flipkart.com/api/4/search","https://2.rome.api.flipkart.com/api/4/discover/autosuggest"];for(const u of urls){for(const body of [JSON.stringify({query:"laptop",contextUri:"/search?q=laptop",marketPlaceId:"FLIPKART",rows:20}),JSON.stringify({query:"laptop",q:"laptop",rows:20}),""]){try{const r=await req(u,{method:"POST",headers:{"content-type":"application/json","accept":"application/json","origin":"https://www.flipkart.com","referer":"https://www.flipkart.com/search?q=laptop"},body});OUT.flipkart.direct.push({url:r.url,status:r.status,ct:r.ct,bytes:r.text.length,productish:prod(r.text),sample:trim(r.text,7000),body})}catch{}}}}
async function acer(){const urls=["https://store.acer.com/en-in/","https://store.acer.com/en-in/graphql","https://store.acer.com/graphql","https://store.acer.com/en-in/rest/V1/products?searchCriteria%5BpageSize%5D=20&searchCriteria%5BcurrentPage%5D=1","https://store.acer.com/rest/V1/products?searchCriteria%5BpageSize%5D=20&searchCriteria%5BcurrentPage%5D=1"];for(const u of urls)for(const http1 of [true,false]){try{const cmd="curl";const r=await req(u,{headers:{"accept":"application/json,text/html,*/*","x-forwarded-proto":"https","store":"default","referer":"https://store.acer.com/en-in/"}});OUT.acer.direct.push({url:r.url,status:r.status,ct:r.ct,bytes:r.text.length,productish:prod(r.text),sample:trim(r.text,5000)})}catch(e){OUT.acer.errors.push({url:u,error:String(e)})}}}
await apple();await flipkart();await acer();await writeFile("left-targets-v2.json",JSON.stringify(OUT,null,2));for(const [k,v] of Object.entries(OUT))console.log("\n=="+k+"==\n"+JSON.stringify({pages:v.pages?.length,direct:v.direct.length,scripts:v.scripts?.length,network:v.network?.length,errors:v.errors?.length,productDirect:v.direct.filter(x=>x.productish).slice(0,10).map(x=>({url:x.url,status:x.status,ct:x.ct}))},null,2));