#!/usr/bin/env node
const sites=JSON.parse(process.env.SITES_JSON||"[]");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const same=(a,b)=>{try{return new URL(a).hostname.replace(/^www\./,"")===new URL(b).hostname.replace(/^www\./,"")}catch{return false}};
const native=(s)=>{const t=String(s||"");return (/^\s*(?:<\?xml[^>]*>\s*)?<rss\b/i.test(t)||/^\s*(?:<\?xml[^>]*>\s*)?<feed\b/i.test(t))&&(/http:\/\/base\.google\.com\/ns\/1\.0|https:\/\/base\.google\.com\/ns\/1\.0/i.test(t))&&/<item\b/i.test(t)&&/<g:(?:id|title|link|price)\b/i.test(t)&&!/just a moment|cf-chl-|turnstile|captcha|access denied|attention required/i.test(t)};
async function get(url,ms=25000){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/140 Safari/537.36","Accept":"text/html,application/xml,text/xml,*/*;q=.2"}});return{status:r.status,url:r.url,ct:r.headers.get("content-type")||"",body:await r.text()}}catch(e){return{status:0,url,error:String(e?.name||e)}}finally{clearTimeout(tm)}}
function extractSearchTargets(html,root){const out=new Set();const s=String(html||"");for(const raw of s.split(/href=/i).slice(1)){let v=raw.trim();if(v[0]==='"'||v[0]==="'")v=v.slice(1);const q=v.indexOf(v[0]);if(q<1)continue;v=v.slice(0,q);v=v.replace(/&amp;/g,"&");try{const u=new URL(v,new URL(root).origin).href;if(same(u,root)&&(/\.xml(?:\.gz)?(?:$|[?#])/i.test(u)||/woocommerce_gpf|woo[-_ ]?feed|ctxfeed|wppfm|google|merchant|shopping|product[-_ ]?feed/i.test(u)))out.add(u);else{for(const key of ["q","url","u","uddg"]){const z=new URL(v,"https://search.invalid").searchParams.get(key);if(z){const dec=decodeURIComponent(z);if(/^https?:\/\//i.test(dec)&&same(dec,root))out.add(dec)}}}}catch{}}for(const token of s.split(/\s+/)){const clean=token.replace(/["'<>),;]+$/g,"");if(/^https?:\/\//i.test(clean)&&same(clean,root)&&(/\.xml(?:\.gz)?(?:$|[?#])/i.test(clean)||/woocommerce_gpf|woo[-_ ]?feed|ctxfeed|wppfm|google|merchant|shopping|product[-_ ]?feed/i.test(clean)))out.add(clean)}return out}
async function live(u,root){const r=await get(u,20000);return{url:u,status:r.status,final:r.url,ct:r.ct,len:r.body?.length||0,native:r.status===200&&same(r.url,root)&&native(r.body)}}
async function probe(site){const root=site.url.replace(/\/$/,""),queries=[
"site:"+new URL(root).hostname+" \"woocommerce_gpf=google\"",
"site:"+new URL(root).hostname+" \"google product feed\"",
"site:"+new URL(root).hostname+" \"product feed\" XML",
"site:"+new URL(root).hostname+" \"base.google.com/ns/1.0\"",
"site:"+new URL(root).hostname+" filetype:xml google merchant",
"site:"+new URL(root).hostname+" \"google-shopping\" XML"
],engines=["https://www.google.com/search","https://www.bing.com/search"],urls=new Set(),searchlog=[];
for(const q of queries){for(const e of engines){const sr=await get(e+"?q="+encodeURIComponent(q),25000);searchlog.push({engine:e,status:sr.status});if(sr.status===200)for(const u of extractSearchTargets(sr.body,root))urls.add(u);await sleep(250)}}const evidence=[];for(const u of urls){const v=await live(u,root);evidence.push(v);if(v.native)return{site:site.name,url:v.final,method:"search_index_live_validation",candidates:urls.size,searchlog,evidence:evidence.slice(-20)}}return{site:site.name,url:null,method:null,candidates:urls.size,searchlog,evidence:evidence.slice(-40)}}
(async()=>{const out=[];for(const s of sites)out.push(await probe(s));console.log(JSON.stringify({native_google_xml_only:true,source:"public_search_index+live_validation",results:out},null,2))})().catch(e=>{console.error(e.stack||e);process.exitCode=1})