#!/usr/bin/env node
const sites=JSON.parse(process.env.SITES_JSON||"[]");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const same=(a,b)=>{try{return new URL(a).hostname.replace(/^www\./,"")===new URL(b).hostname.replace(/^www\./,"")}catch{return false}};
const nativeText=s=>{const t=String(s||"");return /^\s*(?:<\?xml[^>]*>\s*)?<rss\b/i.test(t)&&/https?:\/\/base\.google\.com\/ns\/1\.0/i.test(t)&&/<item\b/i.test(t)&&/<g:id\b/i.test(t)&&/<g:title\b/i.test(t)&&/<g:link\b/i.test(t)&&/<g:price\b/i.test(t)&&/<g:availability\b/i.test(t)&&!/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human/i.test(t)};
async function http(url,ms=20000){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"User-Agent":"Mozilla/5.0 (compatible; NativeGoogleFeedCCHunt/2026.09)","Accept":"application/xml,application/rss+xml,text/xml,text/html;q=.8,*/*;q=.2"}});return{status:r.status,url:r.url,ct:r.headers.get("content-type")||"",body:await r.text()}}catch(e){return{status:0,url,error:String(e?.name||e)}}finally{clearTimeout(tm)}}
async function ccJson(url){const r=await http(url,45000);if(r.status!==200)return{ok:false,status:r.status,error:r.body?.slice(0,200)};const rows=[];for(const line of r.body.split(/\r?\n/)){if(!line.trim())continue;try{rows.push(JSON.parse(line))}catch{}}return{ok:true,status:r.status,rows}}
async function live(url){const d=await http(url,20000);return d.status===200&&nativeText(d.body)&&same(d.url,url)?{ok:true,url:d.url,status:d.status,ct:d.ct,len:d.body.length}:{ok:false,status:d.status,url:d.url,ct:d.ct,len:d.body?.length||0}}
async function coll(){const r=await http("https://index.commoncrawl.org/collinfo.json",30000);if(r.status!==200)throw new Error("collinfo status "+r.status);const a=JSON.parse(r.body);return a.slice(0,3).map(x=>x.id)}
function candidate(u){return /(?:woocommerce_gpf=google|\/woocommerce_gpf\/|[?&]woo_feed=|[?&]feed=[^&#\s]+|\/wp-content\/uploads\/woo-feed\/google\/xml\/|\/wp-content\/uploads\/wppfm-feeds\/|google(?:-|_)?(?:product|shopping|merchant).*\.xml(?:[?#]|$)|(?:^|\/)merchant(?:-|_)?feed.*\.xml(?:[?#]|$)|(?:^|\/)product[-_]?feed.*\.xml(?:[?#]|$))/i.test(u)}
async function probe(site,indices){const root=site.url.replace(/\/$/,"");const candidates=new Set(),sources=[];for(const idx of indices){const q=new URL("https://index.commoncrawl.org/"+idx+"-index");q.searchParams.set("url",root+"/*");q.searchParams.set("output","json");q.searchParams.set("filter","status:200");q.searchParams.set("collapse","urlkey");q.searchParams.set("limit","500");const r=await ccJson(q.href);sources.push({index:idx,ok:r.ok,status:r.status,rows:r.rows?.length||0,error:r.error||null});if(r.ok)for(const row of r.rows||[]){const u=row.url;if(u&&same(u,root)&&candidate(u))candidates.add(u)}await sleep(1000)}const checked=[];for(const u of candidates){const v=await live(u);checked.push({url:u,ok:v.ok,status:v.status,final:v.url,ct:v.ct,len:v.len,source:"commoncrawl-url-index"});if(v.ok)return{site:site.name,url:u,method:"commoncrawl_url_index_live_validation",tested:checked.length,candidates:candidates.size,indices,sources,evidence:checked.slice(-20)}}return{site:site.name,url:null,method:null,tested:checked.length,candidates:candidates.size,indices,sources,evidence:checked.slice(-30)}}
(async()=>{const indices=await coll();const results=[];for(const s of sites)results.push(await probe(s,indices));console.log(JSON.stringify({native_google_xml_only:true,source:"commoncrawl_url_index+live_validation",indices,results},null,2))})().catch(e=>{console.error(e.stack||e);process.exitCode=1})