const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const same=(a,b)=>{try{return new URL(a).hostname.replace(/^www\./,'')===new URL(b).hostname.replace(/^www\./,'')}catch{return false}};
let cid=0;
function cdp(s,method,params={},timeout=45000,sessionId=''){return new Promise((resolve,reject)=>{const id=++cid;let done=false;const timer=setTimeout(()=>{finish();reject(new Error('CDP timeout '+method))},timeout);const finish=()=>{if(done)return;done=true;clearTimeout(timer);s.removeEventListener('message',onMessage);s.removeEventListener('close',onClose)};const onClose=()=>{finish();reject(new Error('CDP closed'))};const onMessage=e=>{try{const m=JSON.parse(typeof e.data==='string'?e.data:new TextDecoder().decode(e.data));if(m.id!==id)return;finish();if(m.error)reject(new Error(m.error.message||method));else resolve(m.result||{})}catch(err){finish();reject(err)}};s.addEventListener('message',onMessage);s.addEventListener('close',onClose);try{s.send(JSON.stringify(sessionId?{id,method,params,sessionId}:{id,method,params}))}catch(err){finish();reject(err)}})}
async function ev(s,expr,sessionId=''){return (await cdp(s,'Runtime.evaluate',{expression:expr,awaitPromise:true,returnByValue:true,generatePreview:false},45000,sessionId)).result?.value}
const json=(x,n=200)=>new Response(JSON.stringify(x),{status:n,headers:{'content-type':'application/json','cache-control':'no-store'}});
export default {async fetch(req,env){
 try{
  const input=req.method==='POST'?await req.json():{};const root=String(input.root||'').trim().replace(/\/$/,'');const targets=[...new Set((input.targets||[]).map(x=>String(x||'').trim()).filter(Boolean))].map(x=>{try{return new URL(x,root).href}catch{return null}}).filter(x=>x&&same(x,root)).slice(0,200);
  if(!root||!targets.length)return json({success:false,error:'missing_root_or_targets'},400);
  const session=await env.BROWSER.launch();const rr=await session.webSocket.fetch('https://browser-binding.invalid',{headers:{Upgrade:'websocket'}});if(!rr.webSocket)throw new Error('no websocket');const s=rr.webSocket;s.accept();
  let targetId='',sessionId='';
  try{
   const created=await cdp(s,'Target.createTarget',{url:root}); targetId=created.targetId||''; if(!targetId)throw new Error('Target.createTarget returned no targetId');
   const attached=await cdp(s,'Target.attachToTarget',{targetId,flatten:true}); sessionId=attached.sessionId||''; if(!sessionId)throw new Error('Target.attachToTarget returned no sessionId');
   const pc=(method,params={},timeout=45000)=>cdp(s,method,params,timeout,sessionId);
   await pc('Page.enable');await pc('Runtime.enable');await pc('Network.enable');
   let page={title:'',readyState:'',challenge:true};const end=Date.now()+30000;
   while(Date.now()<end){await sleep(1500);page=await ev(s,"(()=>({title:document.title||'',readyState:document.readyState,challenge:/just a moment|cf-chl-|cf-browser-verification|cf-mitigated|turnstile|captcha|access denied|attention required|checking your browser|verify you are human/i.test(document.documentElement?.outerHTML||'')}))()",sessionId)||page;if(page.readyState==='complete'&&!page.challenge)break}
   const expression="(async()=>{const root="+JSON.stringify(root)+",targets="+JSON.stringify(targets)+";const bad=/just a moment|cf-chl-|cf-browser-verification|cf-mitigated|turnstile|captcha|access denied|attention required|checking your browser|verify you are human/i;const ns='http://base.google.com/ns/1.0';const same=(a,b)=>{try{return new URL(a).hostname.replace(/^www\./,'')===new URL(b).hostname.replace(/^www\./,'')}catch{return false}};const native=t=>{try{if(bad.test(t)||!/^\\s*(?:<\\?xml[^>]*>\\s*)?<rss\\b/i.test(t))return false;const d=new DOMParser().parseFromString(t,'application/xml');if(!d||d.getElementsByTagName('parsererror').length||String(d.documentElement?.localName||'').toLowerCase()!=='rss')return false;for(const item of [...d.getElementsByTagName('*')].filter(n=>(n.localName||'').toLowerCase()==='item')){const f=n=>{const a=[...item.getElementsByTagNameNS(ns,n)];return a.length?String(a[0].textContent||'').trim():''};if(f('id')&&f('title')&&f('link')&&f('price')&&f('availability'))return true}return false}catch{return false}};const out=[];let hit=null;for(const x of targets){try{const r=await fetch(x,{credentials:'include',redirect:'follow',headers:{accept:'application/xml,application/rss+xml,text/xml,text/plain,*/*'}});const t=await r.text();const rec={url:x,status:r.status,final:r.url,ct:r.headers.get('content-type')||'',len:t.length,challenge:bad.test(t),native:native(t)};out.push(rec);if(rec.native&&same(r.url,root)){hit={url:r.url,method:'browser_session',status:r.status,ct:rec.ct,len:t.length};break}}catch(e){out.push({url:x,status:0,error:String(e)})}}return {hit,statuses:out}})()";
   const result=await ev(s,expression,sessionId);let cookie_names=[];try{const c=await cdp(s,'Network.getAllCookies',{},45000,sessionId);cookie_names=[...new Set((c.cookies||[]).filter(x=>x.name).map(x=>String(x.name)))].slice(0,100)}catch{}
   return json({success:true,root,page,result:result||{},cookie_names,has_cf_clearance:cookie_names.includes('cf_clearance')});
  }finally{try{if(targetId)await cdp(s,'Target.closeTarget',{targetId},20000)}catch{} try{s.close()}catch{}try{await env.BROWSER.closeSession(session.sessionId)}catch{}}
 }catch(e){return json({success:false,error:String(e&&e.stack||e)},500)}}
};