#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
const TARGETS=[["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Variety Infotech","https://varietyinfotech.com"]];
const TIMEOUT=10000,RETRIES=2,RETRY_DELAYS=[2500,6000],UA="Mozilla/5.0 (compatible; WooCommerceWPFactoryRecovery/10.0)";
const CHALLENGE=/just a moment|cf-chl-|cf-turnstile|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i,NS=/https?:\/\/base\.google\.com\/ns\/1\.0/i;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const host=u=>{try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}},same=(a,b)=>host(a)!==""&&host(a)===host(b);
const abs=(root,p)=>{const u=new URL(p,root);return same(u.href,root)?u.href:null};
function validate(body){const x=String(body||"");if(!x.trim())return{valid:false,reason:"empty"};if(CHALLENGE.test(x.slice(0,40000)))return{valid:false,reason:"challenge_or_access_denied"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(x))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(x))return{valid:false,reason:"not_xml"};if(!NS.test(x))return{valid:false,reason:"no_google_namespace"};const bs=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);if(!bs.length)return{valid:false,reason:"no_item_or_entry"};const good=bs.filter(b=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(b))).length;return{valid:good>0,reason:good?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:good}}
async function fetchOnce(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"application/xml,text/xml,application/rss+xml,text/html;q=0.5,*/*;q=0.1","accept-language":"en-IN,en;q=0.9"}});const body=Buffer.from(await r.arrayBuffer()).toString("utf8").slice(0,16*1024*1024);return{status:r.status,final_url:r.url||url,content_type:r.headers.get("content-type")||"",body,transport:r.ok?"public_http":"http_error",challenge:CHALLENGE.test(body.slice(0,40000))}}catch(e){return{status:0,final_url:url,content_type:"",body:"",transport:e?.name==="AbortError"?"timeout":"request_error",challenge:false}}finally{clearTimeout(t)}}
async function probe(url){let last,attempts=0;for(let i=0;i<=RETRIES;i++){attempts++;last=await fetchOnce(url);if(!(last.status===403||last.status===429||last.transport==="timeout"))break;if(i<RETRIES)await sleep(RETRY_DELAYS[i])}const validation=last.status===200&&same(last.final_url,url)?validate(last.body):{valid:false,reason:"http_or_redirect"};return{...last,attempts,validation}}
async function run(site,root){const rows=[],p=abs(root,"/products.xml"),r=await probe(p);rows.push({stage:"representative",url:p,...r});if(r.status===200&&!r.challenge&&!["not_xml","empty","sitemap"].includes(r.validation.reason)){for(const raw of ["/products_2.xml","/products_3.xml","/feeds/google.xml","/feeds/google-shopping.xml","/feeds/google-shopping-feed.xml"]){const u=abs(root,raw);rows.push({stage:"family_expansion",url:u,...await probe(u)})}}const hits=rows.filter(x=>x.validation.valid&&same(x.final_url,root)),signal=rows.some(x=>x.status===200&&!x.challenge&&!["not_xml","empty","sitemap"].includes(x.validation.reason)),blocked=rows.some(x=>x.status===403||x.status===429||x.transport==="timeout"||x.challenge);return{site,root,status:hits.length?"NATIVE_FEED_VERIFIED":signal?"FAMILY_SIGNAL_NO_NATIVE_FEED":blocked?"TRANSPORT_LIMITED_NO_NATIVE_FEED":"NO_FAMILY_SIGNAL_NO_NATIVE_FEED",family:signal||hits.length?"wpfactory_product_xml_feeds_manager":null,native_hits:hits.map(x=>({url:x.final_url,validation:x.validation})),family_signal:signal,transport_limited:blocked,response_summary:{probes:rows.length,http_200:rows.filter(x=>x.status===200).length,http_404:rows.filter(x=>x.status===404).length,http_403:rows.filter(x=>x.status===403).length,http_429:rows.filter(x=>x.status===429).length,timeouts:rows.filter(x=>x.transport==="timeout").length,challenges:rows.filter(x=>x.challenge).length},evidence:rows.map(x=>({stage:x.stage,url:x.url,status:x.status,final_url:x.final_url,content_type:x.content_type,attempts:x.attempts,transport:x.transport,challenge:x.challenge,validation:x.validation,body_sample:x.body.slice(0,500)}))}}
const shard=Number(process.env.SHARD||1),shards=Number(process.env.SHARDS||6),selected=TARGETS.filter((_,i)=>i%shards+1===shard),outDir="out/woocommerce-wpfactory-v10";await mkdir(outDir,{recursive:true});const results=[];for(const t of selected)results.push(await run(...t));const out={schema:"woocommerce-wpfactory-v10/v1",phase:"documented-family-recovery",target_count:results.length,shard,shards,policy:{public_only:true,no_store_api:true,no_plugin_extraction:true,no_browser:true,no_auth:true,no_bypass:true,no_clearance_cookie_replay:true,no_captcha_bypass:true,no_proxy_rotation:true,no_random_token_enumeration:true},family:{name:"WPFactory Product XML Feeds Manager for WooCommerce",primary:"/products.xml",additional_documented_examples:["/products_2.xml","/products_3.xml","/feeds/google.xml"]},results};await writeFile(outDir+"/shard-"+shard+".json",JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify({shard,target_count:results.length,native_verified:results.filter(x=>x.native_hits.length).length,family_signals:results.filter(x=>x.family_signal).length,transport_limited:results.filter(x=>x.transport_limited).length},null,2));
