import {mkdir,writeFile} from "node:fs/promises";
const targets=[["PC Studio","https://www.pcstudio.in"],["Quickin Computers","https://quickincomputers.com"],["Avikaretails","https://avikaretails.com"],["IT Gadgets Online","https://itgadgetsonline.com"],["Geekbees","https://geekbees.in"],["Ninja Dog","https://ninjadog.in"],["Network IT Store","https://networkitstore.in"],["My Nexus Infosys","https://www.mynexusinfosys.com"],["Solanki Enterprises","https://solankienterprises.com"],["AULA India","https://aulaindia.com"],["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Variety Infotech","https://varietyinfotech.com"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Prime ABGB","https://www.primeabgb.com"],["Kryptronix Gaming","https://kryptronix.in"],["NCL Computer","https://nclcomputer.com"]];
const P=["/","/robots.txt","/sitemap.xml","/sitemap_index.xml","/wp-sitemap.xml","/wp-json/"];
const bad=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i,ns=/base\.google\.com\/ns\/1\.0/i;
const same=(a,b)=>{try{const x=new URL(a),y=new URL(b);return x.hostname.toLowerCase().replace(/^www\./,"")===y.hostname.toLowerCase().replace(/^www\./,"")}catch{return false}};
const feedish=u=>{try{return /\.xml(?:\.gz)?(?:[?#].*)?$/i.test(u)||/(feed|google|merchant|shopping|woo_feed|woocommerce_gpf|wppfm|webtoffee|adtribes)/i.test(new URL(u).pathname+new URL(u).search)}catch{return false}};
const valid=s=>{s=String(s||"");const t=s.trimStart();if(bad.test(s.slice(0,50000)))return{valid:false,reason:"blocked_page"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(t))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(t))return{valid:false,reason:"not_xml"};if(!ns.test(s))return{valid:false,reason:"no_google_namespace"};const bs=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),...[...s.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1])];let n=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))n++;return{valid:n>0,reason:n?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:n}};
function urls(s,root){const out=new Set();for(const re of [/(?:href|src|data-url|feedUrl|feed_url|product_feed)\s*=\s*["']([^"']+)["']/gi,/<loc[^>]*>\s*([^<]+?)\s*<\/loc>/gi,/https?:\/\/[^\s<>"']+/gi])for(const m of String(s||"").matchAll(re)){try{const u=new URL((m[1]??m[0]).replace(/[),.;]+$/,""),root);if(same(u.href,root)&&feedish(u.href))out.add(u.href)}catch{}}return[...out]}
async function inspect(browser,name,root){
 const c=await browser.newContext({javaScriptEnabled:true,acceptDownloads:false});const cap=[],pages=[];
 try{
  await c.route("**/*",async route=>{const m=(route.request().method()||"GET").toUpperCase();if(["GET","HEAD","OPTIONS"].includes(m))await route.continue();else await route.abort()});
  const page=await c.newPage();
  page.on("response",async r=>{try{const u=r.url(),m=(r.request().method()||"GET").toUpperCase();if(m!=="GET"||!same(u,root)||cap.length>=160)return;const ct=await r.headerValue("content-type")||"",link=await r.headerValue("link")||"";let body="";try{body=(await r.body()).toString("utf8").slice(0,1200000)}catch{};cap.push({url:u,status:r.status(),content_type:ct,link,bytes:body.length,body})}catch{}});
  for(const p of P){const u=new URL(p,root).href;try{await page.goto(u,{waitUntil:"domcontentloaded",timeout:p==="/"?18000:9000});await page.waitForTimeout(p==="/"?1400:300)}catch{}pages.push({path:p,url:page.url(),status:200})}
  const candidates=new Map(),add=(u,source)=>{try{const v=new URL(u,root).href;if(same(v,root)&&feedish(v))candidates.set(v,{url:v,source})}catch{}};
  for(const r of cap){for(const u of urls(r.body,r.url))add(u,"browser_body");for(const u of urls(r.link,root))add(u,"link_header");add(r.url,"browser_response")}
  const checked=[];for(const cnd of candidates.values()){try{const r=await fetch(cnd.url,{redirect:"follow",headers:{"accept":"application/xml,text/xml,*/*;q=0.1"}}),body=await r.text(),v=r.status===200&&same(r.url,root)?valid(body):{valid:false,reason:"http_or_redirect"};checked.push({url:cnd.url,source:cnd.source,status:r.status,final_url:r.url,validation:v});if(v.valid)return{site:name,root,status:"NATIVE_FEED_VERIFIED",winner:checked.at(-1),pages,cap:capped(cap),candidate_count:candidates.size}}catch{}}
  const challenge=cap.some(x=>bad.test(x.body||""))||pages.some(x=>x.path==="/"&&/4\d\d/.test(String(x.status)));return{site:name,root,status:challenge?"BROWSER_BLOCKED":"NO_NATIVE_FEED_VERIFIED",pages,cap:capped(cap),candidate_count:candidates.size,checked};
 }finally{await c.close()}
}
function capped(a){return a.map(x=>({url:x.url,status:x.status,content_type:x.content_type,link:x.link,bytes:x.bytes,body:x.body?.slice(0,180000)}))}
const outDir="out/woocommerce-browser-feed-v18";await mkdir(outDir,{recursive:true});let browser;let ix=0;const results=new Array(targets.length);try{const p=await import("playwright");browser=await p.chromium.launch({headless:true});const workers=Array.from({length:4},async()=>{while(true){const i=ix++;if(i>=targets.length)return;try{results[i]=await inspect(browser,...targets[i])}catch(e){results[i]={site:targets[i][0],root:targets[i][1],status:"BROWSER_ERROR",error:String(e)}}}});await Promise.all(workers)}finally{try{await browser?.close()}catch{}}const report={schema:"woocommerce-browser-feed-recovery-v18/v1",generated_at:new Date().toISOString(),target_count:30,acceptance:"current same-host XML with Google Merchant namespace and g:id/g:title/g:link/g:price",policy:{public_read_only:true,state_changing_methods_blocked:true,cookie_injection:false,clearance_replay:false,captcha_bypass:false},results};await writeFile(outDir+"/report.json",JSON.stringify(report,null,2));console.log(JSON.stringify({native_verified:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").length,native_urls:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").map(x=>x.winner.final_url),blocked:results.filter(x=>x.status==="BROWSER_BLOCKED").length,errors:results.filter(x=>x.status==="BROWSER_ERROR").length},null,2));