import {mkdir,writeFile} from "node:fs/promises";
const targets=[
["PC Studio","https://www.pcstudio.in"],["Quickin Computers","https://quickincomputers.com"],["Avikaretails","https://avikaretails.com"],["IT Gadgets Online","https://itgadgetsonline.com"],["Geekbees","https://geekbees.in"],["Ninja Dog","https://ninjadog.in"],["Network IT Store","https://networkitstore.in"],["My Nexus Infosys","https://www.mynexusinfosys.com"],["Solanki Enterprises","https://solankienterprises.com"],["AULA India","https://aulaindia.com"],
["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Variety Infotech","https://varietyinfotech.com"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Prime ABGB","https://www.primeabgb.com"],["Kryptronix Gaming","https://kryptronix.in"],["NCL Computer","https://nclcomputer.com"]];
const DIRS=[
"/wp-content/uploads/woo-feed/","/wp-content/uploads/woo-feed/google/","/wp-content/uploads/woo-feed/google/xml/","/wp-content/uploads/woo-feed/xml/",
"/wp-content/uploads/woo-product-feed-pro/","/wp-content/uploads/woo-product-feed-pro/xml/",
"/wp-content/uploads/wppfm-feeds/","/wp-content/uploads/webtoffee_product_feed/",
"/wp-content/uploads/woocommerce-gpf/","/wp-content/uploads/google-product-feed/"
];
const bad=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const ns=/base\.google\.com\/ns\/1\.0/i;
const same=(a,b)=>{try{const x=new URL(a),y=new URL(b);return x.hostname.toLowerCase().replace(/^www\./,"")===y.hostname.toLowerCase().replace(/^www\./,"")}catch{return false}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function validate(s){s=String(s||"");const t=s.trimStart();if(bad.test(s.slice(0,50000)))return{valid:false,reason:"blocked_page"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(t))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(t))return{valid:false,reason:"not_xml"};if(!ns.test(s))return{valid:false,reason:"no_google_namespace"};const bs=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),...[...s.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1])];let n=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))n++;return{valid:n>0,reason:n?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:n}};
function listingUrls(body,dir,root){const s=String(body||""),out=new Set();for(const re of [/(?:href|src)\s*=\s*["']([^"']+\.xml(?:\?[^"']*)?)["']/gi,/<a[^>]+href=["']([^"']+\.xml(?:\?[^"']*)?)["'][^>]*>/gi,/https?:\/\/[^\s"'<>,]+\.xml(?:\?[^\s"'<>,]+)?/gi])for(const m of s.matchAll(re)){try{const u=new URL((m[1]??m[0]),dir).href;if(same(u,root)&&new URL(u).pathname.toLowerCase().endsWith(".xml"))out.add(u)}catch{}}return[...out]}
async function get(u){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),6000);const r=await fetch(u,{redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; FoundationFeedDirectoryRecovery/21.0)","accept":"text/html,application/xhtml+xml,application/xml,text/xml,*/*;q=0.1"}});const body=await r.text();clearTimeout(t);return{status:r.status,final_url:r.url,content_type:r.headers.get("content-type")||"",body}}catch(e){return{status:0,final_url:u,content_type:"",body:"",error:e?.name==="AbortError"?"timeout":"request_error"}}}
async function run([name,root]){
 const found=[],dirs=[];for(const p of DIRS){const u=new URL(p,root).href,r=await get(u);const xs=listingUrls(r.body,u,root);dirs.push({path:p,status:r.status,content_type:r.content_type,bytes:r.body.length,listing_hits:xs.length});for(const x of xs)found.push({url:x,directory:u})}
 const uniq=[...new Map(found.map(x=>[x.url,x])).values()].slice(0,80),checked=[];
 for(const c of uniq){const r=await get(c.url);const v=r.status===200&&same(r.final_url,root)?validate(r.body):{valid:false,reason:r.error==="timeout"?"timeout":"http_or_redirect"};checked.push({url:c.url,directory:c.directory,status:r.status,final_url:r.final_url,content_type:r.content_type,bytes:r.body.length,validation:v});if(v.valid)return{site:name,root,status:"NATIVE_FEED_VERIFIED",winner:checked.at(-1),dirs,discovered:uniq.length}}
 return{site:name,root,status:"NO_NATIVE_FEED_VERIFIED",dirs,discovered:uniq.length,candidates:uniq,checked:checked.slice(-100)};
}
const outDir="out/woocommerce-feed-directory-v21";await mkdir(outDir,{recursive:true});let i=0;const results=new Array(targets.length);const workers=Array.from({length:5},async()=>{while(true){const n=i++;if(n>=targets.length)return;results[n]=await run(targets[n])}});await Promise.all(workers);const report={schema:"woocommerce-feed-directory-recovery-v21/v1",generated_at:new Date().toISOString(),target_count:30,methods:{public_upload_directory_listing:true,explicit_xml_filename_observation:true,deterministic_validation:true,random_filename_generation:false,state_changing_methods:false},results};await writeFile(outDir+"/report.json",JSON.stringify(report,null,2));console.log(JSON.stringify({native_verified:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").length,native_urls:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").map(x=>x.winner.final_url),sites_with_directory_xml:results.filter(x=>x.discovered>0).map(x=>[x.site,x.discovered]),blocked:results.filter(x=>x.status==="NO_NATIVE_FEED_VERIFIED"&&x.dirs.some(d=>[403,429].includes(d.status))).length},null,2));