import {mkdir,writeFile} from "node:fs/promises";
const targets=[
["PC Studio","pcstudio.in"],["Quickin Computers","quickincomputers.com"],["Avikaretails","avikaretails.com"],["IT Gadgets Online","itgadgetsonline.com"],["Geekbees","geekbees.in"],["Ninja Dog","ninjadog.in"],["Network IT Store","networkitstore.in"],["My Nexus Infosys","mynexusinfosys.com"],["Solanki Enterprises","solankienterprises.com"],["AULA India","aulaindia.com"],["Aarna Computers","aarnacomputers.com"],["Ads Store","adsstore.in"],["EZPZ Solutions","ezpzsolutions.in"],["GamesNComps","gamesncomps.com"],["hotshiftpc","hotshiftpc.com"],["ithunt","ithunt.in"],["KC Computers","kccomputers.co.in"],["KRG KART","krgkart.com"],["PC Kumar Infotech","pckumar.in"],["PCHubShop","pchubshop.com"],["SCL Gaming","sclgaming.in"],["Variety Infotech","varietyinfotech.com"],["Viper PC","viperpc.in"],["Cosmic Byte","thecosmicbyte.com"],["Meckeys","meckeys.com"],["StacksKB","stackskb.com"],["Theproaudio","theproaudio.com"],["Prime ABGB","primeabgb.com"],["Kryptronix Gaming","kryptronix.in"],["NCL Computer","nclcomputer.com"]];
const feed=/(?:\.xml(?:\.gz)?(?:$|[?#])|\/feed(?:\/|$)|merchant|shopping|google|woocommerce_gpf|woo[-_ ]?feed|wppfm|webtoffee|adtribes)/i;
const ns=/base\.google\.com\/ns\/1\.0/i,bad=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const same=(a,b)=>{try{const x=new URL(a),y=new URL(b);return x.hostname.toLowerCase().replace(/^www\./,"")===y.hostname.toLowerCase().replace(/^www\./,"")}catch{return false}};
function valid(s){s=String(s||"");const t=s.trimStart();if(bad.test(s.slice(0,50000)))return{valid:false,reason:"blocked_page"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(t))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(t))return{valid:false,reason:"not_xml"};if(!ns.test(s))return{valid:false,reason:"no_google_namespace"};const bs=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),...[...s.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1])];let n=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))n++;return{valid:n>0,reason:n?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:n}};
async function cdx(domain){const u="https://web.archive.org/cdx/search/cdx?url="+encodeURIComponent(domain+"/*")+"&output=json&fl=original,statuscode,mimetype,timestamp&filter=statuscode:200&collapse=urlkey&limit=12000";try{const r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0 (compatible; FoundationWaybackFeedInventory/23.0)","accept":"application/json"}});return{status:r.status,body:await r.text(),url:u}}catch(e){return{status:0,body:"",error:String(e),url:u}}}
async function get(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(u,{redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; FoundationWaybackFeedValidate/23.0)","accept":"application/xml,text/xml,*/*;q=.1"}});return{status:r.status,final_url:r.url,content_type:r.headers.get("content-type")||"",body:await r.text()}}catch(e){return{status:0,final_url:u,content_type:"",body:"",error:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
async function one([name,domain]){
 const x=await cdx(domain);let rows=[];try{const j=JSON.parse(x.body);for(const row of Array.isArray(j)?j.slice(1):[]){const u=row[0]||"";if(feed.test(u))rows.push({url:u,statuscode:row[1],mimetype:row[2],timestamp:row[3]})}}catch{}
 const uniq=[...new Map(rows.map(r=>[r.url,r])).values()].sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,80);
 const checked=[];let idx=0;
 const workers=Array.from({length:8},async()=>{while(true){const i=idx++;if(i>=uniq.length)return;const rec=uniq[i];const u=rec.url.startsWith("http")?rec.url:"https://"+rec.url;const r=await get(u);if(r.status===200&&same(r.final_url,"https://"+domain)){const v=valid(r.body);checked[i]={...rec,current_status:r.status,current_url:r.final_url,current_content_type:r.content_type,validation:v};if(v.valid)return true}}});
 await Promise.all(workers);
 const winner=checked.find(Boolean)&&checked.find(x=>x?.validation?.valid);
 return{site:name,domain,status:winner?"NATIVE_FEED_VERIFIED":rows.length?"NO_CURRENT_NATIVE_FEED_VERIFIED":"NO_WAYBACK_FEED_CANDIDATES",wayback_status:x.status,record_count:rows.length,candidates:uniq,checked:checked.filter(Boolean),winner};
}
const out="out/woocommerce-wayback-feed-v23";await mkdir(out,{recursive:true});let i=0;const results=new Array(targets.length);const workers=Array.from({length:5},async()=>{while(true){const k=i++;if(k>=targets.length)return;results[k]=await one(targets[k])}});await Promise.all(workers);const wins=results.filter(x=>x.winner);const report={schema:"woocommerce-wayback-feed-inventory-v23/v1",generated_at:new Date().toISOString(),target_count:30,methods:{wayback_cdx_wildcard:true,explicit_historical_url_filter:true,current_revalidation:true,concurrent_validation:8,random_filename_generation:false},results};await writeFile(out+"/report.json",JSON.stringify(report,null,2));console.log(JSON.stringify({native_verified:wins.length,native_urls:wins.map(x=>x.winner.final_url),wayback_candidates:results.reduce((a,x)=>a+x.record_count,0),sites_with_historical_candidates:results.filter(x=>x.record_count>0).map(x=>[x.site,x.record_count])},null,2));