#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
const TARGETS=[["PC Studio","https://www.pcstudio.in"],["Quickin Computers","https://quickincomputers.com"],["Avikaretails","https://avikaretails.com"],["Geekbees","https://geekbees.in"],["Ninja Dog","https://ninjadog.in"],["Network IT Store","https://networkitstore.in"],["My Nexus Infosys","https://www.mynexusinfosys.com"],["Solanki Enterprises","https://solankienterprises.com"],["Only SSD","https://onlyssd.com"],["IT Gadgets Online","https://itgadgetsonline.com"],["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Variety Infotech","https://varietyinfotech.com"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Prime ABGB","https://www.primeabgb.com"],["Kryptronix Gaming","https://kryptronix.in"],["NCL Computer","https://nclcomputer.com"]];
const TIMEOUT=12000,MAX_CANDIDATES=120,UA="Mozilla/5.0 (compatible; WooCommerceXMLDirectRecovery/11.0)";
const CHALLENGE=/just a moment|cf-chl-|cf-turnstile|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const NS=/https?:\\/\\/base\\.google\\.com\\/ns\\/1\\.0/i;
const XML=/\\.xml(?:\\.gz)?(?:[?#].*)?$/i;
const SIGNAL=/(feed|google|merchant|shopping|product|woo|gpf|wpfm|webtoffee|adtribes|ctx)/i;
const host=u=>{try{return new URL(u).hostname.toLowerCase().replace(/^www\\./,"")}catch{return""}};
const same=(a,b)=>host(a)!==""&&host(a)===host(b);
const abs=(root,raw)=>{try{const u=new URL(raw,root);return same(u.href,root)?u.href:null}catch{return null}};
function decode(s){try{return decodeURIComponent(String(s).replaceAll("&amp;","&").replaceAll("&quot;","\\"").replaceAll("&#39;","'"))}catch{return String(s)}}
function validate(body){const x=String(body||"");if(!x.trim())return{valid:false,reason:"empty"};if(CHALLENGE.test(x.slice(0,40000)))return{valid:false,reason:"challenge_or_access_denied"};if(/^\\s*<(?:urlset|sitemapindex)\\b/i.test(x))return{valid:false,reason:"sitemap"};if(!/^\\s*(?:<\\?xml\\b|<rss\\b|<feed\\b|<channel\\b)/i.test(x))return{valid:false,reason:"not_xml"};if(!NS.test(x))return{valid:false,reason:"no_google_namespace"};const bs=[...x.matchAll(/<item\\b[^>]*>([\\s\\S]*?)<\\/item>/gi),...x.matchAll(/<entry\\b[^>]*>([\\s\\S]*?)<\\/entry>/gi)].map(m=>m[1]);if(!bs.length)return{valid:false,reason:"no_item_or_entry"};const good=bs.filter(b=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\\\b[^>]*>[\\s\\S]*?<\\\\/g:"+k+">","i").test(b))).length;return{valid:good>0,reason:good?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:good}}
async function get(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"text/html,application/xml,text/xml,application/rss+xml,*/*;q=0.2"}});const body=Buffer.from(await r.arrayBuffer()).toString("utf8").slice(0,12000000);return{status:r.status,final_url:r.url||url,ct:r.headers.get("content-type")||"",body,challenge:CHALLENGE.test(body.slice(0,40000))}}catch(e){return{status:0,final_url:url,ct:"",body:"",challenge:false,error:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
function extractUrls(text,base){const out=new Set();const s=String(text||"");for(const m of s.matchAll(/(?:href|src|data-url|data-href|loc)=[\"']([^\"']+)[\"']/gi)){const u=abs(base,decode(m[1]));if(u&&same(u,base)&&((XML.test(u)||SIGNAL.test(u)&&/\\.xml(?:[?#].*)?$/i.test(u)))&&!/sitemap/i.test(u))out.add(u)}for(const m of s.matchAll(/https?:\\/\\/[^\\s"'<>]+/gi)){const u=abs(base,decode(m[0].replace(/[),.;]+$/,"")));if(u&&same(u,base)&&(XML.test(u)&&!/sitemap/i.test(u)))out.add(u)}return [...out]}
function searchQueries(hostname){const q=encodeURIComponent("site:"+hostname+" (filetype:xml OR inurl:feed OR inurl:merchant OR inurl:google OR inurl:shopping)");return[
"https://www.google.com/search?q="+q+"&num=20","https://www.bing.com/search?q="+q+"&count=20","https://html.duckduckgo.com/html/?q="+q
]}
function searchExtract(body,base){const out=new Set();const s=String(body||"");for(const m of s.matchAll(/https?:\\/\\/[^\\s"'<>]+/gi)){let raw=decode(m[0]);try{const u=new URL(raw);if(u.hostname.includes("google.")||u.hostname.includes("bing.")||u.hostname.includes("duckduckgo.")){const qp=u.searchParams.get("uddg")||u.searchParams.get("url")||u.searchParams.get("q");if(qp)raw=decode(qp)} }catch{}const u=abs(base,raw);if(u&&same(u,base)&&XML.test(u)&&!/sitemap/i.test(u))out.add(u)}return [...out]}
async function sitemapSeeds(root){const seeds=["/robots.txt","/sitemap.xml","/sitemap_index.xml","/wp-sitemap.xml","/"];
const out=new Set(),visited=new Set();
for(const p of seeds){const u=abs(root,p);if(!u||visited.has(u))continue;visited.add(u);const r=await get(u);if(p==="/robots.txt"){for(const line of r.body.split(/\\r?\\n/)){const m=line.match(/^\\s*Sitemap:\\s*(https?:\\/\\/\\S+)/i);if(m)out.add(m[1].replace(/[<>]+$/,""))}for(const x of extractUrls(r.body,u))out.add(x)}else{for(const x of extractUrls(r.body,u))out.add(x)}}
return [...out].slice(0,80)}
async function run(site,root){
const c=new Map();
const add=(url,source)=>{if(url&&same(url,root)&&!c.has(url)&&c.size<MAX_CANDIDATES)c.set(url,source)};
const seeds=await sitemapSeeds(root);for(const u of seeds)add(u,"public_reference");
const homepage=await get(root);for(const u of extractUrls(homepage.body,root))add(u,"homepage_reference");
for(const q of searchQueries(host(root))){const r=await get(q);for(const u of searchExtract(r.body,root))add(u,"search_index")}
const refCandidates=[...c.keys()].filter(u=>XML.test(u)||SIGNAL.test(u));
const results=[];for(let i=0;i<refCandidates.length;i+=10){const batch=await Promise.all(refCandidates.slice(i,i+10).map(async u=>{const r=await get(u);const v=r.status===200&&same(r.final_url,root)?validate(r.body):{valid:false,reason:"http_or_redirect"};return{url:u,source:c.get(u),status:r.status,final_url:r.final_url,content_type:r.ct,challenge:r.challenge,validation:v}}));results.push(...batch)}
const hits=results.filter(x=>x.validation.valid);return{site,root,candidate_count:c.size,native_urls:[...new Set(hits.map(x=>x.final_url))],hits:hits.slice(0,20),summary:{http_200:results.filter(x=>x.status===200).length,http_403:results.filter(x=>x.status===403).length,http_404:results.filter(x=>x.status===404).length,timeouts:results.filter(x=>x.status===0).length,challenges:results.filter(x=>x.challenge).length},status:hits.length?"NATIVE_FEED_VERIFIED":"NO_NATIVE_FEED_VERIFIED"};
}
const shard=Number(process.env.SHARD||1),shards=Number(process.env.SHARDS||6),selected=TARGETS.filter((_,i)=>i%shards+1===shard);const outDir="out/woocommerce-xml-direct-v11";await mkdir(outDir,{recursive:true});const results=[];for(const t of selected)results.push(await run(...t));const out={schema:"woocommerce-xml-direct-v11/v1",target_count:results.length,shard,shards,policy:{xml_only:true,public_only:true,no_store_api:true,no_product_extraction:true,no_plugin_extraction:true,no_browser:true,no_auth:true,no_bypass:true,no_clearance_cookie_replay:true,no_captcha_bypass:true,no_proxy_rotation:true,no_random_token_enumeration:true},results};await writeFile(outDir+"/shard-"+shard+".json",JSON.stringify(out,null,2)+"\\n");console.log(JSON.stringify({shard,target_count:results.length,native_verified:results.filter(x=>x.native_urls.length).length,native_urls:results.flatMap(x=>x.native_urls)},null,2));
