import {mkdir,writeFile} from "node:fs/promises";
const T=[
["PC Studio","https://www.pcstudio.in","gpf"],["Quickin Computers","https://quickincomputers.com","ctx"],["Avikaretails","https://avikaretails.com","adtribes"],["IT Gadgets Online","https://itgadgetsonline.com","wpfm"],
["Geekbees","https://geekbees.in","google"],["Ninja Dog","https://ninjadog.in","google"],["Network IT Store","https://networkitstore.in","google"],["My Nexus Infosys","https://www.mynexusinfosys.com","google"],["Solanki Enterprises","https://solankienterprises.com","google"],["AULA India","https://aulaindia.com","google"],
["Aarna Computers","https://aarnacomputers.com","unknown"],["Ads Store","https://adsstore.in","unknown"],["EZPZ Solutions","https://www.ezpzsolutions.in","unknown"],["GamesNComps","https://gamesncomps.com","unknown"],["hotshiftpc","https://hotshiftpc.com","unknown"],["ithunt","https://ithunt.in","unknown"],["KC Computers","https://kccomputers.co.in","unknown"],["KRG KART","https://krgkart.com","unknown"],["PC Kumar Infotech","https://pckumar.in","unknown"],["PCHubShop","https://www.pchubshop.com","unknown"],["SCL Gaming","https://sclgaming.in","unknown"],["Variety Infotech","https://varietyinfotech.com","google"],["Viper PC","https://viperpc.in","unknown"],["Cosmic Byte","https://www.thecosmicbyte.com","unknown"],["Meckeys","https://www.meckeys.com","unknown"],["StacksKB","https://stackskb.com","unknown"],["Theproaudio","https://www.theproaudio.com","unknown"],["Prime ABGB","https://www.primeabgb.com","gpf"],["Kryptronix Gaming","https://kryptronix.in","webtoffee"],["NCL Computer","https://nclcomputer.com","webtoffee"]];
const F={
gpf:["/?woocommerce_gpf=google","/woocommerce_gpf/google"],
ctx:["/?woo_feed=google&wt=xml","/?woo_feed=google_shopping&wt=xml","/?woo_feed=google-shopping&wt=xml","/wp-content/uploads/woo-feed/xml/google-shopping.xml","/wp-content/uploads/woo-feed/xml/google.xml","/wp-content/uploads/woo-feed/google-shopping.xml","/wp-content/uploads/woo-feed/google.xml","/wp-content/uploads/woo-feed/google-shopping-feed.xml","/wp-content/uploads/woo-feed/google-products.xml","/wp-content/uploads/woo-feed/feed.xml"],
adtribes:["/wp-content/uploads/woo-product-feed-pro/xml/google.xml","/wp-content/uploads/woo-product-feed-pro/xml/google-shopping.xml","/wp-content/uploads/woo-product-feed-pro/xml/google-shopping-feed.xml","/wp-content/uploads/woo-product-feed-pro/xml/google-products.xml","/wp-content/uploads/woo-product-feed-pro/google.xml","/wp-content/uploads/woo-product-feed-pro/google-shopping.xml","/wp-content/uploads/woo-product-feed-pro/feed.xml"],
wpfm:["/wp-content/uploads/wppfm-feeds/google.xml","/wp-content/uploads/wppfm-feeds/Google.xml","/wp-content/uploads/wppfm-feeds/Google-Products.xml","/wp-content/uploads/wppfm-feeds/Google-Feed.xml","/wp-content/uploads/wppfm-feeds/google-feed.xml","/wp-content/uploads/wppfm-feeds/google-products-feed.xml","/wp-content/uploads/wppfm-feeds/google-shopping.xml","/wp-content/uploads/wppfm-feeds/google-shopping-feed.xml","/wp-content/uploads/wppfm-feeds/feed.xml"],
webtoffee:["/wp-content/uploads/webtoffee_product_feed/wt_google_Feed.xml","/wp-content/uploads/webtoffee_product_feed/wt_gs_Feed.xml","/wp-content/uploads/webtoffee_product_feed/wt_google_feed.xml","/wp-content/uploads/webtoffee_product_feed/wt_google_shopping_Feed.xml","/wp-content/uploads/webtoffee_product_feed/google.xml","/wp-content/uploads/webtoffee_product_feed/google-shopping.xml","/wp-content/uploads/webtoffee_product_feed/google-shopping-feed.xml","/wp-content/uploads/webtoffee_product_feed/feed.xml"],
google:[],unknown:[]};
const G=["/google.xml","/google_feed.xml","/google-feed.xml","/google-products.xml","/google-product-feed.xml","/google-shopping.xml","/google-shopping-feed.xml","/google-merchant.xml","/merchant.xml","/product-feed.xml","/feed/google.xml","/feeds/google.xml","/feed.xml"];
const P=["/","/robots.txt","/sitemap.xml","/sitemap_index.xml","/wp-sitemap.xml"];
const UA="Mozilla/5.0 (compatible; WooCommerceXMLLiveRecovery/15.2)",BLOCK=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|sorry, you have been blocked|request blocked/i;
const host=v=>{try{return new URL(v).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}},same=(a,b)=>!!host(a)&&host(a)===host(b);
const abs=(b,r)=>{try{const u=new URL(String(r||"").trim(),b);if(!/^https?:$/.test(u.protocol)||!same(u.href,b))return null;u.hash="";return u.href}catch{return null}};
const like=u=>{try{const x=new URL(u);return /\.xml(?:\.gz)?(?:[?#].*)?$/i.test(x.href)||/(feed|google|merchant|shopping|woocommerce_gpf|woo_feed|gpf|wppfm|webtoffee|adtribes)/i.test(x.pathname+x.search)}catch{return false}};
async function get(u,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(u,{redirect:"follow",signal:c.signal,headers:{"User-Agent":UA,"Accept":"application/xml,text/xml,application/rss+xml,text/html;q=0.9,*/*;q=0.1"}});const b=Buffer.from(await r.arrayBuffer());let body=b.toString("utf8");if(b[0]===31&&b[1]===139){try{const{gunzipSync}=await import("node:zlib");body=gunzipSync(b).toString("utf8")}catch{}}return{status:r.status,final_url:r.url||u,content_type:r.headers.get("content-type")||"",bytes:b.length,body:body.slice(0,16*1024*1024),error:""}}catch(e){return{status:0,final_url:u,content_type:"",bytes:0,body:"",error:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
function validate(x){const s=String(x||""),h=s.slice(0,60000);if(!h.trim())return{valid:false,reason:"empty"};if(BLOCK.test(h))return{valid:false,reason:"challenge_or_access_denied"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(h))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(h))return{valid:false,reason:"not_xml"};if(!/(?:https?:)?\/\/base\.google\.com\/ns\/1\.0/i.test(h))return{valid:false,reason:"no_google_namespace"};const blocks=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),...[...s.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1])];let good=0;for(const b of blocks)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))good++;return{valid:good>0,reason:good?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:blocks.length,valid_items:good}}
function refs(text,b){const out=new Set(),s=String(text||"");for(const re of [/(?:href|src|action|data-url|data-feed-url|feedUrl|feed_url|product_feed)\s*=\s*["']([^"']+)["']/gi,/<loc[^>]*>\s*([^<]+?)\s*<\/loc>/gi,/https?:\/\/[^\s<>"']+/gi])for(const m of s.matchAll(re)){const u=abs(b,m[1]??m[0]);if(u&&like(u))out.add(u)}return[...out]}
async function runSite([name,base,fam]){
 const d=new Map(),add=(u,source,rank)=>{const v=abs(base,u);if(v&&like(v)&&(!d.has(v)||rank>d.get(v).rank))d.set(v,{url:v,source,rank})};
 const pages=[];for(const p of P){const u=new URL(p,base).href,r=await get(u,8000);pages.push({path:p,status:r.status,final_url:r.final_url,bytes:r.bytes,error:r.error});for(const v of refs(r.body,r.final_url||u))add(v,"current_public_reference",500)}
 for(const p of F[fam])add(p,"documented_family_endpoint",350);
 if(fam!=="google")for(const p of G)add(p,"generic_fallback_endpoint",100);
 const cs=[...d.values()].sort((a,b)=>b.rank-a.rank||a.url.localeCompare(b.url)).slice(0,70),checked=[];let next=0,winner=null;
 async function worker(){while(!winner){const i=next++;if(i>=cs.length)return;const c=cs[i],r=await get(c.url),v=r.status===200&&same(r.final_url,base)?validate(r.body):{valid:false,reason:"http_or_redirect"};const row={rank:i+1,...c,status:r.status,final_url:r.final_url,content_type:r.content_type,bytes:r.bytes,error:r.error,validation:v};checked.push(row);if(v.valid)winner=row}}
 await Promise.all(Array.from({length:Math.min(8,cs.length)},worker));
 return{site:name,root:base,family:cFam(fam),candidate_count:cs.length,winner,status:winner?"NATIVE_FEED_VERIFIED":checked.some(x=>x.status===403||x.validation.reason==="challenge_or_access_denied"||x.error==="timeout")?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",discovery_pages:pages,transport_summary:{http_200:checked.filter(x=>x.status===200).length,http_403:checked.filter(x=>x.status===403).length,http_404:checked.filter(x=>x.status===404).length,http_429:checked.filter(x=>x.status===429).length,timeouts:checked.filter(x=>x.error==="timeout").length,challenges:checked.filter(x=>x.validation.reason==="challenge_or_access_denied").length,not_xml:checked.filter(x=>x.validation.reason==="not_xml").length,no_google_namespace:checked.filter(x=>x.validation.reason==="no_google_namespace").length},checked}
}
function cFam(x){return x}
const shard=Number(process.env.SHARD||1),shards=6,picked=T.filter((_,i)=>i%shards+1===shard),outDir="out/woocommerce-xml-live-v15";await mkdir(outDir,{recursive:true});const results=[];for(const t of picked)results.push(await runSite(t));const out={schema:"woocommerce-xml-live-recovery-v15/v1",generated_at:new Date().toISOString(),shard,shards,target_count:results.length,policy:{native_google_merchant_xml_only:true,public_http_only:true,documented_family_endpoints_only:true,no_random_token_enumeration:true,no_store_api:true,no_product_extraction:true,no_auth:true,no_browser_bypass:true,no_clearance_cookie_replay:true,no_captcha_bypass:true,no_proxy_rotation:true},results};await writeFile(outDir+"/shard-"+shard+".json",JSON.stringify(out,null,2)+"\n");console.log(JSON.stringify({shard,target_count:results.length,native_verified:results.filter(x=>x.winner).length,native_urls:results.filter(x=>x.winner).map(x=>x.winner.final_url),transport_limited:results.filter(x=>x.status==="NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED").length},null,2));
