#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
import {gunzipSync} from "node:zlib";
const SITES=[["EZPZ Solutions","https://www.ezpzsolutions.in"],["Aarna Computers","https://aarnacomputers.com"],["StacksKB","https://stackskb.com"],["Viper PC","https://viperpc.in"]];
const F=[
 ["/?woocommerce_gpf=google","gpf"],["/woocommerce_gpf/google","gpf"],["/?woocommerce_gpf=google&gpf_start=0&gpf_limit=1000","gpf"],["/?woocommerce_gpf=google&currency=INR","gpf"],["/?woocommerce_gpf=google&pricecountry=IN","gpf"],
 ["/products.xml","generic"],["/feed.xml","generic"],["/google.xml","generic"],["/google-feed.xml","generic"],["/google-products.xml","generic"],["/google-product-feed.xml","generic"],["/google-shopping.xml","generic"],["/google-shopping-feed.xml","generic"],["/merchant.xml","generic"],["/merchant-feed.xml","generic"],
 ["/wp-content/uploads/google.xml","generic"],["/wp-content/uploads/google-feed.xml","generic"],["/wp-content/uploads/google-products.xml","generic"],["/wp-content/uploads/google-shopping.xml","generic"],
 ["/wp-content/uploads/feed-xml-0.xml","icopydoc"],["/wp-content/uploads/feed-xml.xml","icopydoc"],
 ["/wp-json/feedcraft-product-feed/v1/xml","feedcraft"],["/wp-json/feedcraft-product-feed/v1/google.xml","feedcraft"],["/wp-json/feedcraft-product-feed/v1/google","feedcraft"],
 ["/wp-content/uploads/codesolz-feeds/google.xml","codesolz"],["/wp-content/uploads/codesolz-feeds/google-products.xml","codesolz"],["/wp-content/uploads/codesolz-feeds/google-shopping.xml","codesolz"],
 ["/wp-content/uploads/rex-feed/google.xml","rexfeed"],["/wp-content/uploads/rex-feed/google-products.xml","rexfeed"],["/wp-content/uploads/rex-feed/google-shopping.xml","rexfeed"],
 ["/wp-content/uploads/klp-feeds-xml/google.xml","klpsoft"],["/wp-content/uploads/klp-feeds-xml/google-feed.xml","klpsoft"],["/wp-content/uploads/klp-feeds-xml/google-shopping.xml","klpsoft"],
 ["/wp-content/uploads/woo-feed/google.xml","ctx"],["/wp-content/uploads/woo-feed/google-shopping.xml","ctx"],["/wp-content/uploads/woo-feed/google-shopping-feed.xml","ctx"],["/wp-content/uploads/woo-feed/google-products.xml","ctx"],["/wp-content/uploads/woo-feed/google_shopping_ctx_1.xml","ctx"],["/wp-content/uploads/woo-feed/listings07.xml","ctx"],
 ["/wp-content/uploads/wppfm-feeds/google.xml","wpfm"],["/wp-content/uploads/wppfm-feeds/Google-Products-New.xml","wpfm"],["/wp-content/uploads/wppfm-feeds/Google-Feed_1.xml","wpfm"],["/wp-content/uploads/wppfm-feeds/google-products.xml","wpfm"],
 ["/wp-content/uploads/webtoffee_product_feed/wt_google_Feed.xml","webtoffee"],["/wp-content/uploads/webtoffee_product_feed/wt_gs_Feed.xml","webtoffee"],["/wp-content/uploads/webtoffee_product_feed/wt_gmc_Feed.xml","webtoffee"],
 ["/wp-content/uploads/woo-product-feed-pro/google.xml","adtribes"],["/wp-content/uploads/woo-product-feed-pro/google-shopping.xml","adtribes"]
];
const UA="Mozilla/5.0 (compatible; WooCommerceGoogleXmlNow/8.0)",TIMEOUT=7000,CH=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required/i,NS="base.google.com/ns/1.0";
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
function same(a,b){return host(a)==host(b)&&host(a)!==""}
function native(b){const x=String(b||"");if(!x.trim()||CH.test(x.slice(0,40000))||!/^(?:\s*<\?xml|\s*<rss|\s*<feed|\s*<channel)/i.test(x)||!x.includes(NS))return false;const items=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);return items.some(i=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(i)))}
async function get(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"application/xml,text/xml,application/rss+xml,text/html;q=0.5,*/*;q=0.1"}});let b=Buffer.from(await r.arrayBuffer());if(b[0]===31&&b[1]===139)try{b=gunzipSync(b)}catch{}const body=b.toString("utf8").slice(0,16*1024*1024);return{status:r.status,final_url:r.url||url,body,challenge:CH.test(body.slice(0,40000)),type:r.headers.get("content-type")||""}}catch(e){return{status:0,final_url:url,body:"",challenge:false,type:"",error:e?.name||"error"}}finally{clearTimeout(t)}}
async function siteRun([name,root]){const results=[];for(let i=0;i<F.length;i+=8){const batch=await Promise.all(F.slice(i,i+8).map(async([path,fam])=>{const url=root.replace(/\/$/,"")+path,r=await get(url);return{url,family:fam,...r,verified:r.status===200&&same(r.final_url,root)&&native(r.body)}}));results.push(...batch);const hit=results.find(x=>x.verified);if(hit)return{site:name,root,status:"NATIVE_FEED_VERIFIED",hit,results}}return{site:name,root,status:results.some(x=>x.status===403||x.status===429||x.challenge||x.status===0)?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",hit:null,results}}
const results=await Promise.all(SITES.map(siteRun));await mkdir("out/woocommerce-google-xml-now-v8",{recursive:true});await writeFile("out/woocommerce-google-xml-now-v8/results.json",JSON.stringify({schema:"wc-google-xml-now-v8/v1",results},null,2)+"\n");console.log(JSON.stringify(results.map(x=>({site:x.site,status:x.status,hit:x.hit?.url||null})),null,2));
