#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
const SITES=[
["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Variety Infotech","https://varietyinfotech.com"]];
const Q=['domain ("g:id" OR "g:title" OR "base.google.com/ns/1.0")','domain filetype:xml (google OR merchant OR shopping OR feed)','domain inurl:xml (google OR merchant OR shopping OR feed)','domain inurl:feed (google OR merchant OR shopping OR product)','domain inurl:products.xml','domain inurl:google.xml','domain inurl:google-feed.xml','domain inurl:google-products.xml','domain inurl:product-feed.xml'];
const UA="Mozilla/5.0 (compatible; WooCommerceSearchIndexFeedRecovery/12.0)",TIMEOUT=9000;
const CH=/just a moment|cf-chl-|cf-turnstile|turnstile|captcha|access denied|attention required|checking your browser|request blocked/i,NS="base.google.com/ns/1.0";
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
function same(a,b){return host(a)==host(b)&&host(a)!==""}
function native(b){const x=String(b||"");if(!x.trim()||CH.test(x.slice(0,40000))||!x.includes(NS)||!/^(?:\s*<\?xml|\s*<rss|\s*<feed|\s*<channel)/i.test(x))return false;const bs=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);return bs.some(b=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(b)))}
async function get(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.1"}});const body=Buffer.from(await r.arrayBuffer()).toString("utf8").slice(0,12*1024*1024);return{status:r.status,final_url:r.url||url,body,content_type:r.headers.get("content-type")||"",challenge:CH.test(body.slice(0,40000))}}catch(e){return{status:0,final_url:url,body:"",content_type:"",challenge:false,error:e?.name||"error"}}finally{clearTimeout(t)}}
function urlsFromHtml(html,root){const out=[];for(const m of String(html).matchAll(/https?:[^"'<>\s)]+/gi)){const u=m[0].replace(/[),.;]+$/,"");try{const x=new URL(u);if(/^https?:$/.test(x.protocol)&&same(x.href,root)&&/(?:\.xml(?:\.gz)?(?:$|[?#])|google|merchant|shopping|feed|product[-_]?feed|woocommerce_gpf|woo_feed|wpfm|webtoffee|adtribes|feedcraft|rex[-_]?feed|klp[-_]?feeds|apfw[-_]?feed)/i.test(x.href))out.push(x.href)}catch{}}return out}
async function search(q){const u="https://www.bing.com/search?q="+encodeURIComponent(q)+"&count=50";const r=await get(u);if(r.status!==200)return[];const all=[];for(const m of String(r.body).matchAll(/<a[^>]+href=["'](https?:[^"']+)["']/gi)){try{const x=new URL(m[1]);if(x.hostname.includes("bing.com"))continue;all.push(x.href)}catch{}}return all}
async function run([name,root]){const found=new Set(),evidence=[];for(const q0 of Q){const q=q0.replace("domain","site:"+root);for(const u of await search(q)){if(same(u,root)&&(/\.xml(?:$|\?)|google|merchant|shopping|feed|product[-_]?feed/i.test(u))){found.add(u);evidence.push({query:q,url:u})}}}const candidates=[...found].slice(0,150),results=[];for(let i=0;i<candidates.length;i+=6){results.push(...await Promise.all(candidates.slice(i,i+6).map(async u=>{const r=await get(u);return{url:u,status:r.status,final_url:r.final_url,content_type:r.content_type,challenge:r.challenge,verified:r.status===200&&same(r.final_url,root)&&native(r.body)}})))}const hits=results.filter(x=>x.verified);return{name,root,search_candidates:candidates.length,evidence_count:evidence.length,status:hits.length?"NATIVE_FEED_VERIFIED":results.some(x=>x.status===403||x.status===429||x.challenge||x.status===0)?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",positive_urls:hits.map(x=>x.final_url),hits:hits.slice(0,10)}}
const results=await Promise.all(SITES.map(run));await mkdir("out/woocommerce-search-index-v12",{recursive:true});await writeFile("out/woocommerce-search-index-v12/results.json",JSON.stringify({schema:"wc-search-index-feed-recovery-v12/v1",results},null,2)+"\n");console.log(JSON.stringify(results.map(x=>({site:x.name,search_candidates:x.search_candidates,evidence_count:x.evidence_count,status:x.status,positive_urls:x.positive_urls})),null,2));
