#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
const TARGETS=[
["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],
["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],
["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],
["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Viper PC","https://viperpc.in"],
["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],
["Theproaudio","https://www.theproaudio.com"],["Variety Infotech","https://varietyinfotech.com"]];
const CANDIDATE="/products.xml";
const UA="Mozilla/5.0 (compatible; WooCommerceWPFProductXmlGuess/7.0)";
const CHALLENGE=/just a moment|cf-chl-|cf-turnstile|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const NS=/https?:\/\/base\.google\.com\/ns\/1\.0/i;
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return ""}}
function sameHost(a,b){return host(a)!==""&&host(a)===host(b)}
function native(body){const x=String(body||"");if(!x.trim())return{valid:false,reason:"empty"};if(CHALLENGE.test(x.slice(0,40000)))return{valid:false,reason:"challenge_or_access_denied"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(x))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(x))return{valid:false,reason:"not_xml"};if(!NS.test(x))return{valid:false,reason:"no_google_namespace"};const blocks=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);if(!blocks.length)return{valid:false,reason:"no_item_or_entry"};const good=blocks.filter(b=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(b))).length;return{valid:good>0,reason:good?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:blocks.length,valid_items:good}}
async function probe(root){const url=new URL(CANDIDATE,root).href;const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),7000);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"application/xml,text/xml,application/rss+xml,*/*;q=0.1","accept-language":"en-IN,en;q=0.9"}});let b=Buffer.from(await r.arrayBuffer());if(b[0]===31&&b[1]===139){try{b=gunzipSync(b)}catch{}}const body=b.toString("utf8").slice(0,16*1024*1024);const validation=r.status===200&&sameHost(r.url||url,root)?native(body):{valid:false,reason:"http_or_redirect"};return{candidate:url,status:r.status,final_url:r.url||url,content_type:r.headers.get("content-type")||"",transport:r.ok?"public_http":"http_error",challenge:CHALLENGE.test(body.slice(0,40000)),validation}}catch(e){return{candidate:url,status:0,final_url:url,content_type:"",transport:e?.name==="AbortError"?"timeout":"request_error",challenge:false,validation:{valid:false,reason:"transport_error"}}}finally{clearTimeout(timer)}}
const shard=Number(process.env.SHARD||1),shards=Number(process.env.SHARDS||6);const selected=TARGETS.filter((_,i)=>i%shards+1===shard);
const results=await Promise.all(selected.map(async([site,root])=>{const r=await probe(root);return{site,root,family:"wpfactory_product_xml_feeds",candidate_count:1,candidate_hit:r.validation.valid?[r]:[],positive_urls:r.validation.valid?[r.final_url]:[],status:r.validation.valid?"NATIVE_FEED_VERIFIED":(r.status===403||r.status===429||r.transport==="timeout"||r.challenge)?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",response:r}}));
const out="out/woocommerce-wpfactory-micro-wave-v7";await mkdir(out,{recursive:true});await writeFile(out+"/shard-"+shard+".json",JSON.stringify({schema:"woocommerce-wpfactory-micro-wave-v7/v1",phase:"unknown-micro-wave",shard,shards,target_count:results.length,candidate:CANDIDATE,policy:{public_only:true,no_store_api:true,no_plugin_extraction:true,no_browser_automation:true,no_auth:true,no_clearance_cookie_replay:true,no_captcha_bypass:true,no_proxy_rotation:true,no_random_token_enumeration:true,native_acceptance:"current_same_host_google_merchant_xml_payload"},results},null,2)+"\n");console.log(JSON.stringify({shard,target_count:results.length,native_verified:results.filter(x=>x.positive_urls.length).length,transport_limited:results.filter(x=>x.status.includes("TRANSPORT_LIMITED")).length}));
