import {mkdir,writeFile} from "node:fs/promises";
const targets=[["My Nexus Infosys","https://www.mynexusinfosys.com"],["Solanki Enterprises","https://solankienterprises.com"],["AULA India","https://aulaindia.com"],["hotshiftpc","https://hotshiftpc.com"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Kryptronix Gaming","https://kryptronix.in"]];
const ns=/base\.google\.com\/ns\/1\.0/i,bad=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const same=(a,b)=>{try{const x=new URL(a),y=new URL(b);return x.hostname.toLowerCase().replace(/^www\./,"")===y.hostname.toLowerCase().replace(/^www\./,"")}catch{return false}};
const valid=s=>{s=String(s||"");if(bad.test(s.slice(0,50000)))return{valid:false,reason:"blocked_page"};const t=s.trimStart();if(/^\s*<(?:urlset|sitemapindex)\b/i.test(t))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(t)||!ns.test(s))return{valid:false,reason:"not_current_google_feed"};const bs=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1])];let n=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))n++;return{valid:n>0,reason:n?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:n}};
function extract(v,root){const out=new Set();const s=typeof v==="string"?v:JSON.stringify(v);for(const m of s.matchAll(/https?:\/\/[^\s"'<>,}]+/g)){try{const u=new URL(m[0].replace(/[),.;]+$/,""));if(same(u.href,root)&&(/\.xml(?:\.gz)?/i.test(u.pathname)||/(feed|merchant|shopping|google|catalog)/i.test(u.pathname+u.search)))out.add(u.href)}catch{}}return[...out]}
async function probe(name,root){
 const u=new URL("/wp-json/wc/pos/v1/catalog",root).href;const r=await fetch(u,{redirect:"follow",headers:{"user-agent":"FoundationWooPosCatalogProbe/1.0","accept":"application/json,application/xml,text/xml,*/*;q=.1"}});
 const text=await r.text();let json=null;try{json=JSON.parse(text)}catch{}
 const candidates=new Set(extract(json??text,root));
 const checked=[];const direct=valid(text);if(direct.valid)return{site:name,root,status:"NATIVE_FEED_VERIFIED",source:u,winner:{url:u,status:r.status,content_type:r.headers.get("content-type")||"",validation:direct}};
 for(const c of candidates){try{const x=await fetch(c,{redirect:"follow",headers:{"accept":"application/xml,text/xml,*/*;q=.1"}}),body=await x.text(),v=x.status===200&&same(x.url,root)?valid(body):{valid:false,reason:"http_or_redirect"};checked.push({url:c,status:x.status,final_url:x.url,content_type:x.headers.get("content-type")||"",validation:v});if(v.valid)return{site:name,root,status:"NATIVE_FEED_VERIFIED",source:u,winner:checked.at(-1)}}catch{}}
 return{site:name,root,status:r.status===403||r.status===401?"ROUTE_PROTECTED":"NO_NATIVE_FEED_VERIFIED",route:{url:u,status:r.status,content_type:r.headers.get("content-type")||"",bytes:text.length,body_head:text.slice(0,8000),json},derived_candidates:[...candidates],checked};
}
await mkdir("out/woocommerce-wc-pos-catalog-probe",{recursive:true});const results=await Promise.all(targets.map(t=>probe(...t)));const out={schema:"woocommerce-wc-pos-catalog-probe/v1",generated_at:new Date().toISOString(),target_count:7,route:"/wp-json/wc/pos/v1/catalog",results};await writeFile("out/woocommerce-wc-pos-catalog-probe/report.json",JSON.stringify(out,null,2));console.log(JSON.stringify({native_verified:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").length,native_urls:results.filter(x=>x.status==="NATIVE_FEED_VERIFIED").map(x=>x.winner.final_url||x.winner.url),protected:results.filter(x=>x.status==="ROUTE_PROTECTED").length},null,2));