#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
const SITES=[
["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Viper PC","https://viperpc.in"],["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Variety Infotech","https://varietyinfotech.com"]
];
const UA="Mozilla/5.0 (compatible; WooCommerceCommonCrawlFeedRecovery/11.0)",TIMEOUT=8000,CONCURRENCY=6;
const H=/\.xml(?:\.gz)?(?:$|[?#])|google|merchant|shopping|feed|product[-_]?feed|woocommerce_gpf|woo_feed|wpfm|webtoffee|adtribes|feedcraft|rex[-_]?feed|klp[-_]?feeds|apfw[-_]?feed/i;
const CH=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|request blocked/i;
const NS="base.google.com/ns/1.0";
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
function same(a,b){return host(a)!==""&&host(a)===host(b)}
function abs(root,raw){try{const u=new URL(String(raw),root);if(!/^https?:$/.test(u.protocol)||!same(u.href,root))return null;u.hash="";return u.href}catch{return null}}
function native(b){const x=String(b||"");if(!x.trim()||CH.test(x.slice(0,40000))||!x.includes(NS)||!/^(?:\s*<\?xml|\s*<rss|\s*<feed|\s*<channel)/i.test(x))return false;const items=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);return items.some(i=>["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(i)))}
async function get(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"application/json,application/xml,text/xml,text/html;q=0.5,*/*;q=0.1"}});const body=Buffer.from(await r.arrayBuffer()).toString("utf8").slice(0,14*1024*1024);return{status:r.status,final_url:r.url||url,body,content_type:r.headers.get("content-type")||"",challenge:CH.test(body.slice(0,40000)),transport:r.ok?"public_http":"http_error"}}catch(e){return{status:0,final_url:url,body:"",content_type:"",challenge:false,transport:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
async function latestIndex(){const r=await get("https://index.commoncrawl.org/collinfo.json");if(r.status!==200)return null;try{const rows=JSON.parse(r.body);return rows.find(x=>typeof x?.id==="string"&&/^CC-MAIN-\d{4}-\d{2}$/.test(x.id))?.id||null}catch{return null}}
async function cdx(index,root){const u="https://index.commoncrawl.org/"+index+"-index?url="+encodeURIComponent(root.replace(/\/$/,"")+"/*")+"&matchType=domain&output=json&filter=status:200&collapse=urlkey&limit=1500";const r=await get(u);if(r.status!==200||!r.body)return[];const out=[];for(const line of r.body.split("\n")){if(!line.trim())continue;try{const x=JSON.parse(line);if(H.test(String(x.url||"")))out.push({url:x.url,timestamp:x.timestamp||"",mime:x.mime||"",status:x.status||""})}catch{}}return out.map(x=>({...x,url:abs(root,x.url)})).filter(x=>x.url).slice(0,300)}
async function run([name,root],index){const refs=await cdx(index,root);const uniq=[...new Map(refs.map(x=>[x.url,x])).values()];const results=[];for(let i=0;i<uniq.length;i+=CONCURRENCY){results.push(...await Promise.all(uniq.slice(i,i+CONCURRENCY).map(async h=>{const r=await get(h.url);const ok=r.status===200&&same(r.final_url,root)&&native(r.body);return{...h,...r,verified:ok}})))}const hits=results.filter(x=>x.verified);return{name,root,index,historical_refs:uniq.length,candidate_count:results.length,status:hits.length?"NATIVE_FEED_VERIFIED":results.some(x=>x.status===403||x.status===429||x.transport==="timeout"||x.challenge)?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",positive_urls:hits.map(x=>x.final_url),hits:hits.slice(0,10),summary:{http_200:results.filter(x=>x.status===200).length,http_403:results.filter(x=>x.status===403).length,http_404:results.filter(x=>x.status===404).length,timeouts:results.filter(x=>x.transport==="timeout").length,challenges:results.filter(x=>x.challenge).length}}}
const index=await latestIndex();if(!index)throw new Error("no Common Crawl index");
const results=await Promise.all(SITES.map(s=>run(s,index)));
await mkdir("out/woocommerce-commoncrawl-v11",{recursive:true});
await writeFile("out/woocommerce-commoncrawl-v11/results.json",JSON.stringify({schema:"wc-commoncrawl-feed-recovery-v11/v1",index,results},null,2)+"\n");
console.log(JSON.stringify({index,results:results.map(x=>({site:x.name,historical_refs:x.historical_refs,candidates:x.candidate_count,status:x.status,positive_urls:x.positive_urls}))},null,2));
