#!/usr/bin/env node
import {mkdir,writeFile} from "node:fs/promises";
const TARGETS=[
["Aarna Computers","https://aarnacomputers.com"],["Ads Store","https://adsstore.in"],["EZPZ Solutions","https://www.ezpzsolutions.in"],["GamesNComps","https://gamesncomps.com"],
["hotshiftpc","https://hotshiftpc.com"],["ithunt","https://ithunt.in"],["KC Computers","https://kccomputers.co.in"],["KRG KART","https://krgkart.com"],
["PC Kumar Infotech","https://pckumar.in"],["PCHubShop","https://www.pchubshop.com"],["SCL Gaming","https://sclgaming.in"],["Viper PC","https://viperpc.in"],
["Cosmic Byte","https://www.thecosmicbyte.com"],["Meckeys","https://www.meckeys.com"],["StacksKB","https://stackskb.com"],["Theproaudio","https://www.theproaudio.com"],["Variety Infotech","https://varietyinfotech.com"]
];
const UA="Mozilla/5.0 (compatible; WooCommerceSVMPForgeRecovery/8.0)",TIMEOUT=9000;
const CH=/just a moment|cf-chl-|cf-turnstile|turnstile|captcha|access denied|attention required|checking your browser|request blocked|verify you are human/i;
const NS=/https?:\/\/base\.google\.com\/ns\/1\.0/i;
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,"")}catch{return ""}}
function same(a,b){return host(a)!==""&&host(a)===host(b)}
function abs(root,raw){try{const u=new URL(raw,root);if(!/^https?:$/.test(u.protocol)||!same(u.href,root))return null;u.hash="";return u.href}catch{return null}}
function native(body){const x=String(body||"");if(!x.trim())return{valid:false,reason:"empty"};if(CH.test(x.slice(0,40000)))return{valid:false,reason:"challenge"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(x))return{valid:false,reason:"not_xml"};if(!NS.test(x))return{valid:false,reason:"no_google_namespace"};const bs=[...x.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi),...x.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1]);let good=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[^>]*>[\\s\\S]*?<\\/g:"+k+">","i").test(b)))good++;return{valid:good>0,reason:good?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:good}}
async function get(url){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const r=await fetch(url,{redirect:"follow",signal:ac.signal,headers:{"user-agent":UA,"accept":"application/xml,text/xml,text/html;q=0.8,*/*;q=0.1","accept-language":"en-IN,en;q=0.9"}});const body=Buffer.from(await r.arrayBuffer()).toString("utf8").slice(0,12*1024*1024);return{status:r.status,final_url:r.url||url,body,content_type:r.headers.get("content-type")||"",challenge:CH.test(body.slice(0,40000)),transport:r.ok?"public_http":"http_error"}}catch(e){return{status:0,final_url:url,body:"",content_type:"",challenge:false,transport:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
async function cdx(root,pattern){const u="https://web.archive.org/cdx/search/cdx?url="+encodeURIComponent(root.replace(/\/$/,"")+pattern)+"&output=json&fl=original,statuscode,mimetype,timestamp&filter=statuscode:200&collapse=urlkey&limit=300";const r=await get(u);if(r.status!==200||!r.body)return[];try{const rows=JSON.parse(r.body);return(Array.isArray(rows)?rows.slice(1):[]).map(x=>({url:x?.[0]||"",timestamp:x?.[3]||""})).filter(x=>x.url).slice(0,300)}catch{return[]}}
async function run(name,root){const refs=await cdx(root,"/apfw-feed/*.xml");const uniq=[...new Set(refs.map(x=>x.url))].map(u=>abs(root,u)).filter(Boolean);const candidates=uniq.slice(0,120);const results=[];for(let i=0;i<candidates.length;i+=4){results.push(...await Promise.all(candidates.slice(i,i+4).map(async u=>{const r=await get(u);const v=r.status===200&&same(r.final_url,root)?native(r.body):{valid:false,reason:"http_or_redirect"};return{url:u,status:r.status,final_url:r.final_url,content_type:r.content_type,challenge:r.challenge,transport:r.transport,validation:v}})))}const hits=results.filter(x=>x.validation.valid);return{site:name,root,family:"svmpforge_product_feed",historical_reference_count:refs.length,candidate_count:candidates.length,hits,positive_urls:hits.map(x=>x.final_url),status:hits.length?"NATIVE_FEED_VERIFIED":results.some(x=>x.status===403||x.status===429||x.transport==="timeout"||x.challenge)?"NO_NATIVE_FEED_VERIFIED_TRANSPORT_LIMITED":"NO_NATIVE_FEED_VERIFIED",transport_summary:{http_200:results.filter(x=>x.status===200).length,http_403:results.filter(x=>x.status===403).length,http_404:results.filter(x=>x.status===404).length,timeouts:results.filter(x=>x.transport==="timeout").length,challenges:results.filter(x=>x.challenge).length}}}
const shard=Number(process.env.SHARD||1),shards=6;const selected=TARGETS.filter((_,i)=>i%shards+1===shard);const outDir="out/woocommerce-svmpforge-v8";await mkdir(outDir,{recursive:true});const results=await Promise.all(selected.map(x=>run(...x)));const p={schema:"woocommerce-svmpforge-v8/v1",phase:"new-family-historical-reference-recovery",shard,shards,target_count:results.length,policy:{public_only:true,no_token_enumeration:true,no_auth:true,no_clearance_cookie_replay:true,no_captcha_bypass:true,native_acceptance:"current_same_host_google_merchant_xml_payload"},results};await writeFile(outDir+"/shard-"+shard+".json",JSON.stringify(p,null,2)+"\n");console.log(JSON.stringify({shard,target_count:results.length,native_verified:results.filter(x=>x.hits.length).length,historical_refs:results.reduce((n,x)=>n+x.historical_reference_count,0)},null,2));
