import {mkdir,writeFile} from "node:fs/promises";
const targets=[
["PC Studio","pcstudio.in"],["Quickin Computers","quickincomputers.com"],["Avikaretails","avikaretails.com"],["IT Gadgets Online","itgadgetsonline.com"],["Geekbees","geekbees.in"],["Ninja Dog","ninjadog.in"],["Network IT Store","networkitstore.in"],["My Nexus Infosys","mynexusinfosys.com"],["Solanki Enterprises","solankienterprises.com"],["AULA India","aulaindia.com"],["Aarna Computers","aarnacomputers.com"],["Ads Store","adsstore.in"],["EZPZ Solutions","ezpzsolutions.in"],["GamesNComps","gamesncomps.com"],["hotshiftpc","hotshiftpc.com"],["ithunt","ithunt.in"],["KC Computers","kccomputers.co.in"],["KRG KART","krgkart.com"],["PC Kumar Infotech","pckumar.in"],["PCHubShop","pchubshop.com"],["SCL Gaming","sclgaming.in"],["Variety Infotech","varietyinfotech.com"],["Viper PC","viperpc.in"],["Cosmic Byte","thecosmicbyte.com"],["Meckeys","meckeys.com"],["StacksKB","stackskb.com"],["Theproaudio","theproaudio.com"],["Prime ABGB","primeabgb.com"],["Kryptronix Gaming","kryptronix.in"],["NCL Computer","nclcomputer.com"]];
const FEED=/(?:\.xml(?:\.gz)?(?:$|[?#])|feed|merchant|shopping|google|woo[-_ ]?(?:feed|gpf)|wppfm|webtoffee|adtribes|gpf)/i;
const NS=/base\.google\.com\/ns\/1\.0/i;
const bad=/just a moment|cf-chl-|turnstile|captcha|access denied|attention required|checking your browser|verify you are human|request blocked/i;
const same=(a,b)=>{try{const x=new URL(a),y=new URL(b);return x.hostname.toLowerCase().replace(/^www\./,"")===y.hostname.toLowerCase().replace(/^www\./,"")}catch{return false}};
const validate=s=>{s=String(s||"");const t=s.trimStart();if(bad.test(s.slice(0,50000)))return{valid:false,reason:"blocked_page"};if(/^\s*<(?:urlset|sitemapindex)\b/i.test(t))return{valid:false,reason:"sitemap"};if(!/^\s*(?:<\?xml\b|<rss\b|<feed\b|<channel\b)/i.test(t))return{valid:false,reason:"not_xml"};if(!NS.test(s))return{valid:false,reason:"no_google_namespace"};const bs=[...[...s.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),...[...s.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(m=>m[1])];let n=0;for(const b of bs)if(["id","title","link","price"].every(k=>new RegExp("<g:"+k+"\\b[\\s\\S]*?<\\/g:"+k+">","i").test(b)))n++;return{valid:n>0,reason:n?"validated_google_merchant_xml":"no_item_with_core_google_fields",items:bs.length,valid_items:n}};
async function cdx(domain){
 const u="https://web.archive.org/cdx/search/cdx?url="+encodeURIComponent(domain+"/*")+"&output=json&fl=original,statuscode,mimetype,timestamp&filter=statuscode:200&collapse=urlkey&limit=20000";
 const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);
 try{const r=await fetch(u,{signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; FoundationWaybackFeedInventory/22.0)"}});const b=await r.text();return{status:r.status,body:b,url:u}}catch(e){return{status:0,body:"",error:e?.name==="AbortError"?"timeout":"request_error"}}finally{clearTimeout(t)}}
async function get(u){try{const r=await fetch(u,{redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; FoundationWaybackFeedValidate/22.0)","accept":"application/xml,text/xml,*/*;q=.1"}});return{status:r.status,final_url:r.url,content_type:r.headers.get("content-type")||"",body:await r.text()}}catch(e){return{status:0,final_url:u,content_type:"",body:"",error:e?.name==="AbortError"?"timeout":"request_error"}}}
async function one([name,domain]){
 const x=await cdx(domain);let records=[];try{const j=JSON.parse(x.body);if(Array.isArray(j)&&j.length>1){for(const row of j.slice(1)){const u=row[0]||"";if(FEED.test(u))records.push({url:u,statuscode:row[1],mimetype:row[2],timestamp:row[3]})}}}catch{}
 const unique=[...new Map(records.map(r=>[r.url,r])).values()].slice(0,250),checks=[];for(const rec of unique){const u=rec.url.startsWith("http")?rec.url:"https://"+rec.url;const r=await get(u);if(r.status===200&&same(r.final_url,"https://"+domain)){const v=validate(r.body);checks.push({...rec,current_status:r.status,current_url:r.final_url,current_content_type:r.content_type,validation:v});if(v.valid)return{site:name,domain,status:"NATIVE_FEED_VERIFIED",winner:checks.at(-1),wayback_status:x.status,record_count:records.length}}}
 return{site:name,domain,status:records.length?"NO_CURRENT_NATIVE_FEED_VERIFIED":"NO_WAYBACK_FEED_CANDIDATES",wayback_status:x.status,record_count:records.length,candidates:unique,checks:checks.slice(0,250),wayback_error:x.error||null};
}
const out="out/woocommerce-wayback-feed-v22";await mkdir(out,{recursive:true});let i=0;const results=new Array(targets.length);const workers=Array.from({length:5},async()=>{while(true){const k=i++;if(k>=targets.length)return;results[k]=await one(targets[k])}});await Promise.all(workers);const report={schema:"woocommerce-wayback-feed-inventory-v22/v1",generated_at:new Date().toISOString(),target_count:30,methods:{wayback_cdx_wildcard:true,current_revalidation:true,restrict_to_explicit_historical_urls:true,random_filename_generation:false},results};await writeFile(out+"/report.json",JSON.stringify(report,null,2));const n=results.filter(x=>x.status==="NATIVE_FEED_VERIFIED");console.log(JSON.stringify({native_verified:n.length,native_urls:n.map(x=>x.winner.final_url||x.winner.url),wayback_candidates:results.reduce((a,x)=>a+x.record_count,0),sites_with_wayback_candidates:results.filter(x=>x.record_count>0).map(x=>[x.site,x.record_count])},null,2));