name: workflow syntax lint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions workflow lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nicholas-fedor/actionlint-action@78fd91fa48051abcbeac14c695a0921b0a71e9a1 # actionlint-action
        with:
          version: "1.7.12"
          shellcheck: ""
          pyflakes: ""
